package br.com.hardsoftware.mercearia.view;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import br.com.hardsoftware.mercearia.control.FuncionarioControle;
import br.com.hardsoftware.mercearia.dao.CidadeDao;
import br.com.hardsoftware.mercearia.dao.EstadoDao;
import br.com.hardsoftware.mercearia.dao.FuncionarioDao;
import br.com.hardsoftware.mercearia.model.Cidade;
import br.com.hardsoftware.mercearia.model.Estado;
import br.com.hardsoftware.mercearia.model.Funcionario;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.border.LineBorder;

/**
 *
 * @author Erbert
 */
public class CadastroFuncionario extends javax.swing.JDialog {

    public CadastroFuncionario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        panelDadosPessoais = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblDtNasc = new javax.swing.JLabel();
        javax.swing.text.MaskFormatter maskNasc= null;
        try{
            maskNasc= new javax.swing.text.MaskFormatter("##/##/####");
            maskNasc.setPlaceholderCharacter('_');

        }
        catch (java.text.ParseException exc) {}
        txtDtNasc = 
        new javax.swing.JFormattedTextField(maskNasc);
        ;
        lblSexo = new javax.swing.JLabel();
        cbSexo = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        lblCpf = new javax.swing.JLabel();
        lblRg = new javax.swing.JLabel();
        javax.swing.text.MaskFormatter maskTel = null;
        try{
            maskTel= new javax.swing.text.MaskFormatter("(##)#####-####");

        }
        catch (java.text.ParseException exc) {}
        txtCelular = 
        new javax.swing.JFormattedTextField(maskTel);
        lblTelefone = new javax.swing.JLabel();
        javax.swing.text.MaskFormatter maskCel = null;
        try{
            maskCel= new javax.swing.text.MaskFormatter("(##)####-####");

        }
        catch (java.text.ParseException exc) {}
        txtTelefone = new javax.swing.JFormattedTextField(maskCel);
        lblCelular = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        javax.swing.text.MaskFormatter maskCpf = null;
        try{
            maskCpf= new javax.swing.text.MaskFormatter("###.###.###-##");

        }
        catch (java.text.ParseException exc) {}
        txtCpf = new javax.swing.JFormattedTextField(maskCpf);
        txtRg = new javax.swing.JTextField();
        panelEnderecoAcesso = new javax.swing.JPanel();
        txtEndereco = new javax.swing.JTextField();
        cbUf = new javax.swing.JComboBox();
        EstadoDao ed = new EstadoDao();
        ArrayList estadoList = ed.findAll();
        for (int i = 0; i <estadoList.size(); i++) {
            cbUf.addItem(estadoList.get(i));
        }
        lblEndreco = new javax.swing.JLabel();
        lblUf = new javax.swing.JLabel();
        lblCep = new javax.swing.JLabel();
        javax.swing.text.MaskFormatter maskCEP = null; try{ maskCEP= new javax.swing.text.MaskFormatter("##.###-###"); maskCEP.setPlaceholderCharacter('_');  } catch (java.text.ParseException exc) {}
        txtCep = new javax.swing.JFormattedTextField(maskCEP);
        lblCidade = new javax.swing.JLabel();
        cbCidade = new javax.swing.JComboBox();
        lblSalario = new javax.swing.JLabel();
        txtSalario = new javax.swing.JTextField();
        lblLogin = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        lblSenha = new javax.swing.JLabel();
        lblCargo = new javax.swing.JLabel();
        cboCargo = new javax.swing.JComboBox();
        txtSenha = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Cliente");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/hardsoftware/mercearia/images/Icone Cliente - Ax54.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        lblTitulo.setText("Cadastro de Funcionários");

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        lblNome.setText("Nome completo:");

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        lblDtNasc.setText("Data de Nasc.:");

        txtDtNasc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDtNasc.setToolTipText("Teste");
        txtDtNasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDtNascActionPerformed(evt);
            }
        });

        lblSexo.setText("Sexo:");

        cbSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Feminino" }));
        cbSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSexoActionPerformed(evt);
            }
        });

        lblCpf.setText("CPF:");

        lblRg.setText("RG:");

        txtCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCelularActionPerformed(evt);
            }
        });

        lblTelefone.setText("Telefone:");

        txtTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefoneActionPerformed(evt);
            }
        });

        lblCelular.setText("Celular:");

        lblEmail.setText("E-mail:");

        javax.swing.GroupLayout panelDadosPessoaisLayout = new javax.swing.GroupLayout(panelDadosPessoais);
        panelDadosPessoais.setLayout(panelDadosPessoaisLayout);
        panelDadosPessoaisLayout.setHorizontalGroup(
            panelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDadosPessoaisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDadosPessoaisLayout.createSequentialGroup()
                        .addGroup(panelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDadosPessoaisLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(lblSexo))
                            .addComponent(cbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCelular))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTelefone)
                            .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmail)
                            .addComponent(txtEmail)))
                    .addGroup(panelDadosPessoaisLayout.createSequentialGroup()
                        .addGroup(panelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDadosPessoaisLayout.createSequentialGroup()
                                .addGap(259, 259, 259)
                                .addComponent(jLabel15))
                            .addGroup(panelDadosPessoaisLayout.createSequentialGroup()
                                .addComponent(lblNome)
                                .addGap(142, 142, 142)
                                .addComponent(lblCpf)
                                .addGap(67, 67, 67)
                                .addComponent(lblRg))
                            .addGroup(panelDadosPessoaisLayout.createSequentialGroup()
                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtRg, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDtNasc)
                            .addComponent(txtDtNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20))
        );
        panelDadosPessoaisLayout.setVerticalGroup(
            panelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDadosPessoaisLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelDadosPessoaisLayout.createSequentialGroup()
                        .addGroup(panelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNome)
                            .addComponent(lblCpf)
                            .addComponent(lblRg)
                            .addComponent(lblDtNasc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDtNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDadosPessoaisLayout.createSequentialGroup()
                                .addComponent(lblSexo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelDadosPessoaisLayout.createSequentialGroup()
                                .addGroup(panelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblTelefone)
                                    .addComponent(lblCelular))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(panelDadosPessoaisLayout.createSequentialGroup()
                        .addComponent(lblEmail)
                        .addGap(26, 26, 26)))
                .addGap(66, 66, 66)
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Dados Pessoais", panelDadosPessoais);

        txtEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnderecoActionPerformed(evt);
            }
        });

        cbUf.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbUfItemStateChanged(evt);
            }
        });
        cbUf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbUfActionPerformed(evt);
            }
        });

        lblEndreco.setText("Endereço:");

        lblUf.setText("UF:");

        lblCep.setText("CEP:");

        txtCep.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCep.setToolTipText("Teste");
        txtCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCepActionPerformed(evt);
            }
        });

        lblCidade.setText("Cidade:");

        cbCidade.removeAllItems();
        CidadeDao cd = new CidadeDao();
        ArrayList cidadeList = cd.findByEstado((Estado) cbUf.getSelectedItem());
        for (int i = 0; i <cidadeList.size(); i++) {
            cbCidade.addItem(cidadeList.get(i));
        }
        cbCidade.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbCidadeItemStateChanged(evt);
            }
        });
        cbCidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbCidadeMouseClicked(evt);
            }
        });
        cbCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCidadeActionPerformed(evt);
            }
        });

        lblSalario.setText("Salário:");

        txtSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalarioActionPerformed(evt);
            }
        });

        lblLogin.setText("Login:");

        txtLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginActionPerformed(evt);
            }
        });

        lblSenha.setText("Senha:");

        lblCargo.setText("Cargo:");

        cboCargo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Operador", "Super Operador", "Administrador", "Gerente" }));
        cboCargo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboCargoItemStateChanged(evt);
            }
        });
        cboCargo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboCargoMouseClicked(evt);
            }
        });
        cboCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCargoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelEnderecoAcessoLayout = new javax.swing.GroupLayout(panelEnderecoAcesso);
        panelEnderecoAcesso.setLayout(panelEnderecoAcessoLayout);
        panelEnderecoAcessoLayout.setHorizontalGroup(
            panelEnderecoAcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEnderecoAcessoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEnderecoAcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEnderecoAcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(panelEnderecoAcessoLayout.createSequentialGroup()
                            .addGroup(panelEnderecoAcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelEnderecoAcessoLayout.createSequentialGroup()
                                    .addComponent(lblCep)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lblEndreco))
                            .addGap(18, 18, 18)
                            .addComponent(lblUf)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cbUf, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblCidade)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cbCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelEnderecoAcessoLayout.createSequentialGroup()
                            .addGroup(panelEnderecoAcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblSalario)
                                .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(panelEnderecoAcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblLogin)
                                .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(24, 24, 24)
                            .addGroup(panelEnderecoAcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblSenha)
                                .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(lblCargo)
                        .addComponent(txtEndereco))
                    .addComponent(cboCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89))
        );
        panelEnderecoAcessoLayout.setVerticalGroup(
            panelEnderecoAcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEnderecoAcessoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEnderecoAcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCep)
                    .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUf)
                    .addComponent(cbUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCidade)
                    .addComponent(cbCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEndreco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelEnderecoAcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSalario)
                    .addComponent(lblLogin)
                    .addComponent(lblSenha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEnderecoAcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblCargo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtCep.getAccessibleContext().setAccessibleName("");
        txtCep.getAccessibleContext().setAccessibleDescription("");

        jTabbedPane3.addTab(" Endereço e Acesso", panelEnderecoAcesso);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/hardsoftware/mercearia/images/print.png"))); // NOI18N
        jButton1.setText("Imprimir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitulo)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnSalvar)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnderecoActionPerformed

    private void FDtBatismoAguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FDtBatismoAguaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_FDtBatismoAguaActionPerformed

    private void CEleitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CEleitorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CEleitorActionPerformed

    private void FLocalBatismoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FLocalBatismoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FLocalBatismoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        boolean vazio = false;
        boolean cpfvalido = Funcionario.validaCpf(txtCpf.getText());
        if(txtNome.getText().equals("")){
             CadastroFuncionario.campoObrigatorio(txtNome);
             vazio = true;
        }
        if(txtCpf.getText().equals("   .   .   -  ")){
            CadastroFuncionario.campoObrigatorio(txtCpf);
            vazio = true;
        }else{
            if(!cpfvalido){
            campoObrigatorio(txtCpf);
            JOptionPane.showMessageDialog(null, "CPF Inválido", "Erro - Dados Inválidos", JOptionPane.ERROR_MESSAGE);
            vazio = true;
            }
        }
        if(txtRg.getText().equals("")){
            CadastroFuncionario.campoObrigatorio(txtRg);
            vazio = true;
        }
        if(txtDtNasc.getText().equals("__/__/____")){
            CadastroFuncionario.campoObrigatorio(txtDtNasc);
            vazio = true;
        }
        if(txtCelular.getText().equals("(  )     -    ")){
            CadastroFuncionario.campoObrigatorio(txtCelular);
            vazio = true;
        }
        if(txtTelefone.getText().equals("(  )    -    ")){
            CadastroFuncionario.campoObrigatorio(txtTelefone);
            vazio = true;
        }
        if(txtEmail.getText().equals("")){
            CadastroFuncionario.campoObrigatorio(txtEmail);
            vazio = true;
        }
        if(txtCep.getText().equals("__.___-___")){
            CadastroFuncionario.campoObrigatorio(txtCep);
            vazio = true;
        }
        if(txtEndereco.getText().equals("")){
            CadastroFuncionario.campoObrigatorio(txtEndereco);
            vazio = true;
        }
        if(vazio == false){
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Existem campos vazios", "Erro - Campo Vazio", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void cbUfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbUfActionPerformed
        
    }//GEN-LAST:event_cbUfActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        cancel = true;
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void FDtDecisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FDtDecisaoActionPerformed

    }//GEN-LAST:event_FDtDecisaoActionPerformed

    private void txtCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCepActionPerformed

    private void FDtCasamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FDtCasamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FDtCasamentoActionPerformed

    private void FDtBatismoEspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FDtBatismoEspActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FDtBatismoEspActionPerformed

    private void CGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CGrupoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CGrupoActionPerformed

    private void CAdmissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CAdmissaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CAdmissaoActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void CCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CCargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CCargoActionPerformed

    private void txtCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCelularActionPerformed

    private void txtTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefoneActionPerformed

    private void FProfissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FProfissaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FProfissaoActionPerformed

    private void CEstCivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CEstCivilActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_CEstCivilActionPerformed

    private void CEstCivilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CEstCivilMouseClicked

    }//GEN-LAST:event_CEstCivilMouseClicked

    private void CEscolaridadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CEscolaridadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CEscolaridadeActionPerformed

    private void cbSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSexoActionPerformed

    }//GEN-LAST:event_cbSexoActionPerformed

    private void txtDtNascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDtNascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDtNascActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void CUFNaturalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CUFNaturalidadeActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_CUFNaturalidadeActionPerformed

    private void CNaturalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CNaturalidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CNaturalidadeActionPerformed

    private void FDtBatismoAguaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FDtBatismoAguaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_FDtBatismoAguaMouseClicked

    private void FDtBatismoAguaComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_FDtBatismoAguaComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_FDtBatismoAguaComponentShown

    private void CUFNaturalidadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CUFNaturalidadeMouseClicked
        // TODO add your handling code here:


    }//GEN-LAST:event_CUFNaturalidadeMouseClicked

    private void CCongBatismoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CCongBatismoActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_CCongBatismoActionPerformed

    private void CCongBatismoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CCongBatismoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CCongBatismoMouseClicked

    private void CUFNaturalidadeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CUFNaturalidadeItemStateChanged

    }//GEN-LAST:event_CUFNaturalidadeItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton2ActionPerformed
    DefaultListModel listaGrupo = new DefaultListModel();
    private void txtSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalarioActionPerformed

    private void txtLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginActionPerformed

    private void cbUfItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbUfItemStateChanged
        cbCidade.removeAllItems();
        CidadeDao cd = new CidadeDao();
        ArrayList cidadeList = cd.findByEstado((Estado) cbUf.getSelectedItem());
        for (int i = 0; i <cidadeList.size(); i++) {
            cbCidade.addItem(cidadeList.get(i));
        }
    }//GEN-LAST:event_cbUfItemStateChanged

    private void cbCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCidadeActionPerformed

    private void cbCidadeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbCidadeItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCidadeItemStateChanged

    private void cbCidadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbCidadeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCidadeMouseClicked

    private void cboCargoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboCargoItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cboCargoItemStateChanged

    private void cboCargoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboCargoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cboCargoMouseClicked

    private void cboCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboCargoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FuncionarioDao cd = new FuncionarioDao();
        FuncionarioControle.gerarHtml(cd.findByCpf(txtCpf.getText()));
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    private static CadastroFuncionario tela;

    public static CadastroFuncionario getInstance(java.awt.Frame parent, boolean modal) {
        if (tela == null) {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
             * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
             */
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>
            //</editor-fold>
            tela = new CadastroFuncionario(parent, modal);
            return tela;
        } else {
            return tela;
        }
    }

    public static void mostrar(Funcionario f) {
        CadastroFuncionario dialog = CadastroFuncionario.getInstance(
                new javax.swing.JFrame(), true);
        dialog.prepararMostrar(f);
        dialog.setVisible(true);
        tela = null;
    }

    private static boolean cancel = false;

    public static Funcionario editar(Funcionario f) {
        CadastroFuncionario dialog = CadastroFuncionario.getInstance(
                new javax.swing.JFrame(), true);
        dialog.prepararEditar(f);
        dialog.setVisible(true);
        //Gambiarra
        if (CadastroFuncionario.cancel == true) {
            cancel = false;
            tela = null;
            return f;
        } else {
            f = dialog.getEstadoTela();
            tela = null;
            return f;
        }
    }
    
     public void cidade(String cpf){
        FuncionarioDao fu = new FuncionarioDao();
        Funcionario f = fu.findByCpf(cpf);
        cbUf.setSelectedItem(f.getCidadeFuncionario().getEstado());
        cbCidade.setSelectedItem(f.getCidadeFuncionario());
    }

    public static Funcionario inserir() {
        CadastroFuncionario dialog = CadastroFuncionario.getInstance(
                new javax.swing.JFrame(), true);

        dialog.setVisible(true);
        //Gambiarra
        if (CadastroFuncionario.cancel == true) {
            return null;
        } else {
            return dialog.getEstadoTela();
        }

    }

    public Funcionario getEstadoTela() {
        Funcionario f = new Funcionario();
        f.setNmFuncionario(txtNome.getText());
        f.setCpfFuncionario(txtCpf.getText());
        f.setRgFuncionario(txtRg.getText());
        f.setDtNascFuncionario(txtDtNasc.getText());
        //Confere o Sexo selecionado na combo box e tranforma em char
        char sexo = 'N';
        if (cbSexo.getSelectedItem().equals("Masculino")) {
            sexo = 'M';
        } else if (cbSexo.getSelectedItem().equals("Feminino")) {
            sexo = 'F';
        }
        f.setSexoFuncionario(sexo);
        f.setCelularFuncionario(txtCelular.getText());
        f.setTelefoneFuncionario(txtTelefone.getText());
        f.setEmailFuncionario(txtEmail.getText());
        f.setCepFuncionario(txtCep.getText());
        f.setCidadeFuncionario((Cidade) cbCidade.getSelectedItem()); //Lembrando que ele envia o Objeto cidade, não só o nome
        f.setEnderecoFuncionario(txtEndereco.getText());
        f.setSalarioFuncionario(Double.parseDouble(txtSalario.getText()));
        f.setLoginFunconario(txtLogin.getText());
        f.setSenhaFuncionario(String.copyValueOf(txtSenha.getPassword()));
        f.setCargoFuncionario(cboCargo.getSelectedItem().toString());

        return f;
    }

    public void prepararMostrar(Funcionario f) {

        //Dando Enable para todos componentes pois só vou mostar imformações nessa parte
        txtNome.setEnabled(false);
        txtCpf.setEnabled(false);
        txtRg.setEnabled(false);
        txtDtNasc.setEnabled(false);
        cbSexo.setEnabled(false);
        txtCelular.setEnabled(false);
        txtTelefone.setEnabled(false);
        txtEmail.setEnabled(false);
        txtCep.setEnabled(false);
        cbCidade.setEnabled(false);
        cbUf.setEnabled(false);
        txtEndereco.setEnabled(false);
        txtSalario.setEnabled(false);
        txtLogin.setEnabled(false);
        txtSenha.setEnabled(false);
        cboCargo.setEnabled(false);
        btnSalvar.setVisible(false);
        btnCancelar.setVisible(false);

        //Setando as informações recebidas por parâmetro
        txtNome.setText(f.getNmFuncionario());
        txtCpf.setText(f.getCpfFuncionario());
        txtRg.setText(f.getRgFuncionario());
        txtDtNasc.setText(f.getDtNascFuncionario());

        if (f.getSexoFuncionario() == 'M') {
            cbSexo.setSelectedItem("Masculino");
        } else if (f.getSexoFuncionario() == 'F') {
            cbSexo.setSelectedItem("Feminino");
        }
        txtCelular.setText(f.getCelularFuncionario());
        txtTelefone.setText(f.getTelefoneFuncionario());
        txtEmail.setText(f.getEmailFuncionario());
        txtCep.setText(f.getCepFuncionario());
        for (int i = 0; i < cbUf.getItemCount(); i++) {
           Estado uf = (Estado)cbUf.getItemAt(i);
           if(uf.getCodEstado() == f.getCidadeFuncionario().getEstado().getCodEstado()){
                cbUf.setSelectedItem(cbUf.getItemAt(i));
                break;
           }
               
        }
        cbCidade.removeAllItems();
        CidadeDao cd = new CidadeDao();
        ArrayList cidadeList = cd.findByEstado(f.getCidadeFuncionario().getEstado());
        for (int i = 0; i <cidadeList.size(); i++) {
            cbCidade.addItem(cidadeList.get(i));
        }
        for (int i = 0; i < cbCidade.getItemCount(); i++) {
           Cidade cidade = (Cidade)cbCidade.getItemAt(i);
           if(cidade.getCdCidade() == f.getCidadeFuncionario().getCdCidade()){
                cbCidade.setSelectedItem(cbCidade.getItemAt(i));
                break;
           }
        }
        txtEndereco.setText(f.getEnderecoFuncionario());
        txtSalario.setText(String.valueOf(f.getSalarioFuncionario()));
        txtLogin.setText(f.getLoginFunconario());
        txtSenha.setText(f.getSenhaFuncionario());
        cboCargo.setSelectedItem(f.getCargoFuncionario());
    }

    public void prepararEditar(Funcionario f) {

        //Setando as informações recebidas por parâmetro
        txtNome.setText(f.getNmFuncionario());
        txtCpf.setText(f.getCpfFuncionario());
        txtRg.setText(f.getRgFuncionario());
        txtDtNasc.setText(f.getDtNascFuncionario());

        if (f.getSexoFuncionario() == 'M') {
            cbSexo.setSelectedItem("Masculino");
        } else if (f.getSexoFuncionario() == 'F') {
            cbSexo.setSelectedItem("Feminino");
        }
        txtCelular.setText(f.getCelularFuncionario());
        txtTelefone.setText(f.getTelefoneFuncionario());
        txtEmail.setText(f.getEmailFuncionario());
        txtCep.setText(f.getCepFuncionario());
        for (int i = 0; i < cbUf.getItemCount(); i++) {
           Estado uf = (Estado)cbUf.getItemAt(i);
           if(uf.getCodEstado() == f.getCidadeFuncionario().getEstado().getCodEstado()){
                cbUf.setSelectedItem(cbUf.getItemAt(i));
                break;
           }
               
        }
        cbCidade.removeAllItems();
        CidadeDao cd = new CidadeDao();
        ArrayList cidadeList = cd.findByEstado(f.getCidadeFuncionario().getEstado());
        for (int i = 0; i <cidadeList.size(); i++) {
            cbCidade.addItem(cidadeList.get(i));
        }
        for (int i = 0; i < cbCidade.getItemCount(); i++) {
           Cidade cidade = (Cidade)cbCidade.getItemAt(i);
           if(cidade.getCdCidade() == f.getCidadeFuncionario().getCdCidade()){
                cbCidade.setSelectedItem(cbCidade.getItemAt(i));
                break;
           }
        }
        txtEndereco.setText(f.getEnderecoFuncionario());
        txtSalario.setText(String.valueOf(f.getSalarioFuncionario()));
        txtLogin.setText(f.getLoginFunconario());
        txtSenha.setText(f.getSenhaFuncionario());
        cboCargo.setSelectedItem(f.getCargoFuncionario());
    }
    
    public static void campoObrigatorio(JTextField campo){
        campo.setBackground(Color.yellow);
        campo.setBorder(new LineBorder(Color.RED));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox cbCidade;
    private javax.swing.JComboBox cbSexo;
    private javax.swing.JComboBox cbUf;
    private javax.swing.JComboBox cboCargo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblCep;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblDtNasc;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEndreco;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblRg;
    private javax.swing.JLabel lblSalario;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUf;
    private javax.swing.JPanel panelDadosPessoais;
    private javax.swing.JPanel panelEnderecoAcesso;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JFormattedTextField txtCep;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JFormattedTextField txtDtNasc;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtRg;
    private javax.swing.JTextField txtSalario;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
