package br.com.hardsoftware.mercearia.view;

import br.com.hardsoftware.mercearia.control.FuncionarioControle;
import br.com.hardsoftware.mercearia.dao.FuncionarioDao;
import br.com.hardsoftware.mercearia.model.Funcionario;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Erbert
 */
public class GerenciaFuncionario extends javax.swing.JDialog {


    public GerenciaFuncionario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    ModeloTabelaFuncionario modelFuncionario = new ModeloTabelaFuncionario();
    DefaultTableModel model = modelFuncionario.findAll();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoBotao = new javax.swing.ButtonGroup();
        jProgressBar1 = new javax.swing.JProgressBar();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        lblCodigo = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        btnAdicionar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        lblPesquisa = new javax.swing.JLabel();
        cbSituacao = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblFuncionario = new javax.swing.JTable();
        btnAtivar = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/hardsoftware/mercearia/images/Icone Funcionario- Ax54.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        lblTitulo.setText("Gerência de Funcionário");

        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodigoKeyPressed(evt);
            }
        });

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomeKeyPressed(evt);
            }
        });

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        lblCodigo.setText("Código:");

        lblNome.setText("Nome:");

        btnAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/hardsoftware/mercearia/images/Icone Add - 35 x A.png"))); // NOI18N
        btnAdicionar.setText("Adicionar");
        btnAdicionar.setMaximumSize(new java.awt.Dimension(111, 43));
        btnAdicionar.setMinimumSize(new java.awt.Dimension(111, 43));
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/hardsoftware/mercearia/images/Icone Remove - Ax35.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/hardsoftware/mercearia/images/Icone config - Ax35.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/hardsoftware/mercearia/images/Icone Search - Ax35.png"))); // NOI18N
        btnConsultar.setText("Detalhes");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        lblPesquisa.setText("Pesquisar por:");

        cbSituacao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Funcionários Ativos", "Funcionários Inativos" }));
        cbSituacao.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbSituacaoItemStateChanged(evt);
            }
        });
        cbSituacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSituacaoActionPerformed(evt);
            }
        });

        tblFuncionario.setModel(model);
        tblFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFuncionarioMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblFuncionario);

        btnAtivar.setVisible(false);
        btnAtivar.setText("Ativar");
        btnAtivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtivarActionPerformed(evt);
            }
        });

        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/hardsoftware/mercearia/images/print.png"))); // NOI18N
        btnImprimir.setText("Imprimir");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesquisar))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPesquisa)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnConsultar))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCodigo)
                                .addGap(26, 26, 26)
                                .addComponent(lblNome))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAtivar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitulo)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnConsultar)
                        .addComponent(btnAlterar)
                        .addComponent(btnExcluir))
                    .addComponent(btnAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(lblPesquisa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAtivar))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigo)
                    .addComponent(lblNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnImprimir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSair))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        FuncionarioControle.inserir();
        Atualizar();
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void cbSituacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSituacaoActionPerformed
        /*if (cbSituacao.getSelectedItem().equals("Clientes Ativos")) {
            btnAtivar.setVisible(false);
            model = modelFuncionario.findAll();
            tblFuncionario.setModel(model);
            this.repaint();
        } else {
            btnAtivar.setVisible(true);
            model = modelFuncionario.findAllInative();
            tblFuncionario.setModel(model);
            this.repaint();
        }*/
    }//GEN-LAST:event_cbSituacaoActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        /*int linha = tblFuncionario.getSelectedRow();
        Funcionario f = (Funcionario) tblFuncionario.getValueAt(linha, 1);
        FuncionarioControle.editar(f);
        Atualizar();
        */
        int linha = tblFuncionario.getSelectedRow();
        if(linha == -1){
            JOptionPane.showMessageDialog(null, "Selecione um funcionário", "Erro - Funcionário não selecionado", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            Funcionario f = (Funcionario) tblFuncionario.getValueAt(linha, 1);
            FuncionarioControle.editar(f);
            Atualizar();
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed

        if (cbSituacao.getSelectedItem().equals("Funcionarios Ativos")) {
            if (txtCodigo.getText().equals("")) {
                model = modelFuncionario.findByName(txtNome.getText());
                tblFuncionario.setModel(model);
                this.repaint();
            } else {
                int cod = Integer.parseInt(txtCodigo.getText());
                model = modelFuncionario.findByCod(cod);
                tblFuncionario.setModel(model);
                this.repaint();
            }
        } else if (txtCodigo.getText().equals("")) {
            model = modelFuncionario.findInativeByName(txtNome.getText());
            tblFuncionario.setModel(model);
            this.repaint();
        } else {
            int cod = Integer.parseInt(txtCodigo.getText());
            model = modelFuncionario.findInativeByCod(cod);
            tblFuncionario.setModel(model);
            this.repaint();
        }

    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        /*int linha = tblFuncionario.getSelectedRow();
        Funcionario f = (Funcionario) tblFuncionario.getValueAt(linha, 1);
        int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente desativar " + f + "?", "Excluir Cliente", JOptionPane.YES_NO_OPTION);
        if (resposta == JOptionPane.YES_OPTION) {
            //Usuário clicou em Sim. Executar o código correspondente.
            FuncionarioControle.excluir(f);
        }
        Atualizar();*/
        
        int linha = tblFuncionario.getSelectedRow();
        if(linha == -1){
            JOptionPane.showMessageDialog(null, "Selecione um funcionário", "Erro - Funcionário não selecionado", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            Funcionario f = (Funcionario) tblFuncionario.getValueAt(linha, 1);
            int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente desativar "+f+"?", "Excluir Funcionário", JOptionPane.YES_NO_OPTION);
            if (resposta == JOptionPane.YES_OPTION) {
            //Usuário clicou em Sim. Executar o código correspondente.
            FuncionarioControle.excluir(f);
            }
            Atualizar();
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAtivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtivarActionPerformed
        int linha = tblFuncionario.getSelectedRow();
        Funcionario f = (Funcionario) tblFuncionario.getValueAt(linha, 1);
        FuncionarioControle.ativar(f);
        AtualizarInativo();
    }//GEN-LAST:event_btnAtivarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        /*int linha = tblFuncionario.getSelectedRow();
        Funcionario f = (Funcionario) tblFuncionario.getValueAt(linha, 1);
        FuncionarioControle.mostrar(f);*/
        
        int linha = tblFuncionario.getSelectedRow();
        if(linha == -1){
            JOptionPane.showMessageDialog(null, "Selecione um funcionário", "Erro - Funcionário não selecionado", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            Funcionario f = (Funcionario) tblFuncionario.getValueAt(linha, 1);
            FuncionarioControle.mostrar(f);
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void tblFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFuncionarioMouseClicked
        if (evt.getClickCount() > 1) {
            int linha = tblFuncionario.getSelectedRow();
            Funcionario f = (Funcionario) tblFuncionario.getValueAt(linha, 1);
            FuncionarioControle.mostrar(f);
        }
    }//GEN-LAST:event_tblFuncionarioMouseClicked

    private void txtNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            if (cbSituacao.getSelectedItem().equals("Funcionários Ativos")) {

                model = modelFuncionario.findByName(txtNome.getText());
                tblFuncionario.setModel(model);
                this.repaint();
            } else {
                model = modelFuncionario.findInativeByName(txtNome.getText());
                tblFuncionario.setModel(model);
                this.repaint();
            }
        }
    }//GEN-LAST:event_txtNomeKeyPressed

    private void txtCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (cbSituacao.getSelectedItem().equals("Funcionários Ativos")) {
                int cod = Integer.parseInt(txtCodigo.getText());
                model = modelFuncionario.findByCod(cod);
                tblFuncionario.setModel(model);
                this.repaint();
            } else {
                int cod = Integer.parseInt(txtCodigo.getText());
                model = modelFuncionario.findInativeByCod(cod);
                tblFuncionario.setModel(model);
                this.repaint();
            }
        }
    }//GEN-LAST:event_txtCodigoKeyPressed

    private void cbSituacaoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbSituacaoItemStateChanged

        if(cbSituacao.getSelectedItem().equals("Funcionários Ativos")){
            btnAtivar.setVisible(false);
            model = modelFuncionario.findAll();
            tblFuncionario.setModel(model);
            this.repaint();
        }
        else{
            btnAtivar.setVisible(true);
            model = modelFuncionario.findAllInative();
            tblFuncionario.setModel(model);
            this.repaint();
        }
    }//GEN-LAST:event_cbSituacaoItemStateChanged

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        FuncionarioDao cd  = new FuncionarioDao();
        if(cbSituacao.getSelectedItem().equals("Funcionários Ativos"))
        FuncionarioControle.gerarHtml((ArrayList<Funcionario>) cd.findAll());
        else
        FuncionarioControle.gerarHtml((ArrayList<Funcionario>) cd.findInative());
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    public static void inciar() {
       GerenciaFuncionario dialog = GerenciaFuncionario.getInstance(
                                new javax.swing.JFrame(), true);
        dialog.setVisible(true);
        

    }    
    
    private static GerenciaFuncionario tela;
    public static GerenciaFuncionario getInstance(java.awt.Frame parent, boolean modal) {        
        if (tela == null){
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
             * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
             */
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(GerenciaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(GerenciaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(GerenciaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(GerenciaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>
            
            return new GerenciaFuncionario(parent, modal);        
        }
        else{
            return tela;
        }
    }

    public void Atualizar() {
        model = modelFuncionario.findAll();
        tblFuncionario.setModel(model);
        this.repaint();
    }

    public void AtualizarInativo() {
        model = modelFuncionario.findAllInative();
        tblFuncionario.setModel(model);
        this.repaint();
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GrupoBotao;
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnAtivar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSair;
    private javax.swing.JComboBox cbSituacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPesquisa;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblFuncionario;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
