package br.com.hardsoftware.mercearia.view;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */





import br.com.hardsoftware.mercearia.control.ClienteControle;
import br.com.hardsoftware.mercearia.dao.CidadeDao;
import br.com.hardsoftware.mercearia.dao.ClienteDao;
import br.com.hardsoftware.mercearia.dao.EstadoDao;
import br.com.hardsoftware.mercearia.model.Caixa;
import br.com.hardsoftware.mercearia.model.Cidade;
import br.com.hardsoftware.mercearia.model.Cliente;
import br.com.hardsoftware.mercearia.model.Estado;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.border.LineBorder;


/**
 *
 * @author Alysson
 */
public class CadastroCliente extends javax.swing.JDialog {

    /**
     * Creates new form InserirMembro
     */
    private static Cliente cliente;
    private CadastroCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblNasc = new javax.swing.JLabel();
        javax.swing.text.MaskFormatter maskNasc= null;
        try{
            maskNasc= new javax.swing.text.MaskFormatter("##/##/####");
            maskNasc.setPlaceholderCharacter('_');

        }
        catch (java.text.ParseException exc) {}
        txtDtNasc = 
        new javax.swing.JFormattedTextField(maskNasc);
        ;
        lblSexo = new javax.swing.JLabel();
        cboSexo = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        lblCpf = new javax.swing.JLabel();
        lblRg = new javax.swing.JLabel();
        javax.swing.text.MaskFormatter maskTel = null;
        try{
            maskTel= new javax.swing.text.MaskFormatter("(##)#####-####");

        }
        catch (java.text.ParseException exc) {}
        txtCelular = 
        new javax.swing.JFormattedTextField(maskTel);
        lblTelefone = new javax.swing.JLabel();
        javax.swing.text.MaskFormatter maskCel = null;
        try{
            maskCel= new javax.swing.text.MaskFormatter("(##)####-####");

        }
        catch (java.text.ParseException exc) {}
        txtTelefone = new javax.swing.JFormattedTextField(maskCel);
        lblCelular = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        javax.swing.text.MaskFormatter maskCpf = null;
        try{
            maskCpf= new javax.swing.text.MaskFormatter("###.###.###-##");

        }
        catch (java.text.ParseException exc) {}
        txtCpf = new javax.swing.JFormattedTextField(maskCpf);
        txtRg = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        txtEndereco = new javax.swing.JTextField();
        cboUf = new javax.swing.JComboBox();
        EstadoDao ed = new EstadoDao();
        ArrayList estadoList = ed.findAll();
        for (int i = 0; i <estadoList.size(); i++) {
            cboUf.addItem(estadoList.get(i));
        }
        lblRua = new javax.swing.JLabel();
        lblUf = new javax.swing.JLabel();
        lblCep = new javax.swing.JLabel();
        javax.swing.text.MaskFormatter maskCEP = null; try{ maskCEP= new javax.swing.text.MaskFormatter("##.###-###"); maskCEP.setPlaceholderCharacter('_');  } catch (java.text.ParseException exc) {}
        txtCep = new javax.swing.JFormattedTextField(maskCEP);
        lblCidade = new javax.swing.JLabel();
        cboCidade = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Cliente");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/hardsoftware/mercearia/images/Icone Cliente - Ax54.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jLabel2.setText("Cadastro de Clientes");

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        lblNome.setText("Nome completo:");

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        lblNasc.setText("Data de Nasc.:");

        txtDtNasc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDtNasc.setToolTipText("Teste");
        txtDtNasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDtNascActionPerformed(evt);
            }
        });

        lblSexo.setText("Sexo:");

        cboSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Feminino" }));
        cboSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboSexoActionPerformed(evt);
            }
        });

        lblCpf.setText("CPF:");

        lblRg.setText("RG:");

        txtCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCelularActionPerformed(evt);
            }
        });

        lblTelefone.setText("Telefone:");

        txtTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefoneActionPerformed(evt);
            }
        });

        lblCelular.setText("Celular:");

        lblEmail.setText("E-mail:");

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(lblSexo))
                            .addComponent(cboSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCelular))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTelefone)
                            .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmail)
                            .addComponent(txtEmail)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblNome)
                                .addGap(142, 142, 142)
                                .addComponent(lblCpf))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(259, 259, 259)
                                .addComponent(jLabel15)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRg, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRg))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNasc)
                            .addComponent(txtDtNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(lblCpf)
                    .addComponent(lblRg)
                    .addComponent(lblNasc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDtNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblSexo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTelefone)
                            .addComponent(lblCelular)
                            .addComponent(lblEmail))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(66, 66, 66)
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Dados Pessoais", jPanel2);

        txtEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnderecoActionPerformed(evt);
            }
        });

        cboUf.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboUfItemStateChanged(evt);
            }
        });
        cboUf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboUfActionPerformed(evt);
            }
        });

        lblRua.setText("Endereço:");

        lblUf.setText("UF:");

        lblCep.setText("CEP:");

        txtCep.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCep.setToolTipText("Teste");
        txtCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCepActionPerformed(evt);
            }
        });

        lblCidade.setText("Cidade:");

        cboCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCidadeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCep)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUf)
                            .addComponent(cboUf, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCidade)
                            .addComponent(cboCidade, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(lblRua)
                    .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(220, 220, 220))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCep)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUf)
                    .addComponent(lblCidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(lblRua)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        txtCep.getAccessibleContext().setAccessibleName("");
        txtCep.getAccessibleContext().setAccessibleDescription("");

        jTabbedPane3.addTab(" Endereço", jPanel3);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/hardsoftware/mercearia/images/print.png"))); // NOI18N
        jButton1.setText("Imprimir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnSalvar)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void FDtBatismoAguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FDtBatismoAguaActionPerformed
    }//GEN-LAST:event_FDtBatismoAguaActionPerformed

    private void CEleitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CEleitorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CEleitorActionPerformed

    private void FLocalBatismoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FLocalBatismoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FLocalBatismoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        boolean vazio = false;
        boolean cpfvalido = Cliente.validaCpf(txtCpf.getText());
        if(txtNome.getText().equals("")){
             CadastroCliente.campoObrigatorio(txtNome);
             vazio = true;
        }
        if(txtCpf.getText().equals("   .   .   -  ")){
            CadastroCliente.campoObrigatorio(txtCpf);
            vazio = true;
        }else{
            if(!cpfvalido){
            campoObrigatorio(txtCpf);
            JOptionPane.showMessageDialog(null, "CPF Inválido", "Erro - Dados Inválidos", JOptionPane.ERROR_MESSAGE);
            vazio = true;
            }
        }
        if(txtRg.getText().equals("")){
            CadastroCliente.campoObrigatorio(txtRg);
            vazio = true;
        }
        if(txtDtNasc.getText().equals("__/__/____")){
            CadastroCliente.campoObrigatorio(txtDtNasc);
            vazio = true;
        }
        if(txtCelular.getText().equals("(  )     -    ")){
            CadastroCliente.campoObrigatorio(txtCelular);
            vazio = true;
        }
        if(txtTelefone.getText().equals("(  )    -    ")){
            CadastroCliente.campoObrigatorio(txtTelefone);
            vazio = true;
        }
        if(txtEmail.getText().equals("")){
            CadastroCliente.campoObrigatorio(txtEmail);
            vazio = true;
        }
        if(txtCep.getText().equals("__.___-___")){
            CadastroCliente.campoObrigatorio(txtCep);
            vazio = true;
        }
        if(txtEndereco.getText().equals("")){
            CadastroCliente.campoObrigatorio(txtEndereco);
            vazio = true;
        }
        if(vazio == false){
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Existem campos vazios", "Erro - Campo Vazio", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        cancel = true;
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void FDtDecisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FDtDecisaoActionPerformed

    }//GEN-LAST:event_FDtDecisaoActionPerformed

    private void FDtCasamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FDtCasamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FDtCasamentoActionPerformed

    private void FDtBatismoEspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FDtBatismoEspActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FDtBatismoEspActionPerformed

    private void CGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CGrupoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CGrupoActionPerformed

    private void CAdmissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CAdmissaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CAdmissaoActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void CCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CCargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CCargoActionPerformed

    private void txtCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCelularActionPerformed

    private void txtTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefoneActionPerformed

    private void FProfissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FProfissaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FProfissaoActionPerformed

    private void CEstCivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CEstCivilActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_CEstCivilActionPerformed

    private void CEstCivilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CEstCivilMouseClicked

    }//GEN-LAST:event_CEstCivilMouseClicked

    private void CEscolaridadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CEscolaridadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CEscolaridadeActionPerformed

    private void cboSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboSexoActionPerformed

    }//GEN-LAST:event_cboSexoActionPerformed

    private void txtDtNascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDtNascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDtNascActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void CUFNaturalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CUFNaturalidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CUFNaturalidadeActionPerformed

    private void CNaturalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CNaturalidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CNaturalidadeActionPerformed

    private void FDtBatismoAguaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FDtBatismoAguaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_FDtBatismoAguaMouseClicked

    private void FDtBatismoAguaComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_FDtBatismoAguaComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_FDtBatismoAguaComponentShown

    private void CUFNaturalidadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CUFNaturalidadeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CUFNaturalidadeMouseClicked

    private void CCongBatismoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CCongBatismoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CCongBatismoActionPerformed

    private void CCongBatismoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CCongBatismoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CCongBatismoMouseClicked

    private void CUFNaturalidadeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CUFNaturalidadeItemStateChanged
    }//GEN-LAST:event_CUFNaturalidadeItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    }//GEN-LAST:event_jButton2ActionPerformed
    DefaultListModel listaGrupo = new DefaultListModel();
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ClienteDao cd = new ClienteDao();
        ClienteControle.gerarHtml(cd.findByCpf(txtCpf.getText()));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCepActionPerformed

    private void cboUfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboUfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboUfActionPerformed

    private void txtEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnderecoActionPerformed

    private void cboCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCidadeActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cboCidadeActionPerformed

    private void cboUfItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboUfItemStateChanged
        cboCidade.removeAllItems();
        CidadeDao cd = new CidadeDao();
        ArrayList cidadeList = cd.findByEstado((Estado) cboUf.getSelectedItem());
        for (int i = 0; i <cidadeList.size(); i++) {
            cboCidade.addItem(cidadeList.get(i));
        }
    }//GEN-LAST:event_cboUfItemStateChanged

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private static CadastroCliente tela;
    public static CadastroCliente getInstance(java.awt.Frame parent, boolean modal) {        
        if (tela == null){
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
             * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
             */
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>
            //</editor-fold>
            tela = new CadastroCliente(parent, modal);  
            return tela;
        }
        else{
            return tela;
        }
    }
  
    public void cidade(String cpf){
        ClienteDao cd = new ClienteDao();
        Cliente c = cd.findByCpf(cpf);
        cboUf.setSelectedItem(c.getCidadeCliente().getEstado());
        cboCidade.setSelectedItem(c.getCidadeCliente());
    }
    public static void mostrar(Cliente c) {
        CadastroCliente dialog = CadastroCliente.getInstance(
                                new javax.swing.JFrame(), true);
        dialog.prepararMostrar(c);
        dialog.setVisible(true);
        tela =null;
        
    }
    
    static boolean cancel = false;
    public static Cliente editar(Cliente c) {
        CadastroCliente dialog = CadastroCliente.getInstance(
                                new javax.swing.JFrame(), true);
        dialog.prepararEditar(c);
        dialog.setVisible(true);
        //Gambiarra
        if(CadastroCliente.cancel == true){
            cancel = false;
            tela =null;
            return c;
        }
        else{
            c = dialog.getEstadoTela();
            tela = null;
            return c;
        }
    }
    public static Cliente inserir() {
        CadastroCliente dialog = CadastroCliente.getInstance(
                                new javax.swing.JFrame(), true);
        
        dialog.setVisible(true);
        //Gambiarra
        if(CadastroCliente.cancel == true)
            return null;
        else
            return dialog.getEstadoTela();

    }
    
    public Cliente getEstadoTela(){
        Cliente c = new Cliente();
        c.setNmCliente(txtNome.getText());
        c.setCpfCliente(txtCpf.getText());
        c.setRg(txtRg.getText());
        c.setDtNascCliente(txtDtNasc.getText());
        
        //Confere o Sexo selecionado na combo box e tranforma em char
        char sexo = 'N';
        if(cboSexo.getSelectedItem().equals("Masculino")){
            sexo = 'M';
        }
        else if(cboSexo.getSelectedItem().equals("Feminino")){
            sexo = 'F';
        }
        
        c.setSexoCliente(sexo);
        c.setCelularCliente(txtCelular.getText());
        c.setTelefoneCliente(txtTelefone.getText());
        c.setEmailCliente(txtEmail.getText());
        c.setCepCliente(txtCep.getText());
        c.setCidadeCliente((Cidade)cboCidade.getSelectedItem()); //Lembrando que ele envia o Objeto cidade, não só o nome
        c.setEndereco(txtEndereco.getText());
        return c;
     }
    
    public void prepararMostrar(Cliente c){
        //Dando Enable para todos componentes pois só vou mostar imformações nessa parte
        cliente = c;
        txtNome.setEnabled(false);
        txtCpf.setEnabled(false);
        txtRg.setEnabled(false);
        txtDtNasc.setEnabled(false);
        cboSexo.setEnabled(false);
        txtCelular.setEnabled(false);
        txtTelefone.setEnabled(false);
        txtEmail.setEnabled(false);
        txtCep.setEnabled(false);
        cboCidade.setEnabled(false);
        cboUf.setEnabled(false);
        txtEndereco.setEnabled(false);
        btnSalvar.setVisible(false);
        btnCancelar.setVisible(false);
        //Setando as informações recebidas por parâmetro
        
        txtNome.setText(c.getNmCliente());
        txtCpf.setText(c.getCpfCliente());
        txtRg.setText(c.getRg());
        txtDtNasc.setText(c.getDtNascCliente());
        
        if (c.getSexoCliente() == 'M'){
            cboSexo.setSelectedItem("Masculino");
        }else if (c.getSexoCliente() == 'F'){
            cboSexo.setSelectedItem("Feminino");
        }
            
        txtCelular.setText(c.getCelularCliente());
        txtTelefone.setText(c.getTelefoneCliente());
        txtEmail.setText(c.getEmailCliente());
        txtCep.setText(c.getCepCliente());
        for (int i = 0; i < cboUf.getItemCount(); i++) {
           Estado uf = (Estado)cboUf.getItemAt(i);
           if(uf.getCodEstado() == c.getCidadeCliente().getEstado().getCodEstado()){
                cboUf.setSelectedItem(cboUf.getItemAt(i));
                break;
           }
               
        }
        cboCidade.removeAllItems();
        CidadeDao cd = new CidadeDao();
        ArrayList cidadeList = cd.findByEstado(c.getCidadeCliente().getEstado());
        for (int i = 0; i <cidadeList.size(); i++) {
           cboCidade.addItem(cidadeList.get(i));
        }
        for (int i = 0; i < cboCidade.getItemCount(); i++) {
           Cidade cidade = (Cidade)cboCidade.getItemAt(i);
           if(cidade.getCdCidade() == c.getCidadeCliente().getCdCidade()){
                cboCidade.setSelectedItem(cboCidade.getItemAt(i));
                break;
           }
        }
        txtEndereco.setText(c.getEndereco());
        
    }
    
    public void prepararEditar(Cliente c){
        //Setando as informações recebidas por parâmetro
        cliente = c;
        txtNome.setText(c.getNmCliente());
        txtCpf.setText(c.getCpfCliente());
        txtRg.setText(c.getRg());
        txtDtNasc.setText(c.getDtNascCliente());
        
        if (c.getSexoCliente() == 'M'){
            cboSexo.setSelectedItem("Masculino");
        }else if (c.getSexoCliente() == 'F'){
            cboSexo.setSelectedItem("Feminino");
        }
            
        txtCelular.setText(c.getCelularCliente());
        txtTelefone.setText(c.getTelefoneCliente());
        txtEmail.setText(c.getEmailCliente());
        txtCep.setText(c.getCepCliente());
        for (int i = 0; i < cboUf.getItemCount(); i++) {
           Estado uf = (Estado)cboUf.getItemAt(i);
           if(uf.getCodEstado() == c.getCidadeCliente().getEstado().getCodEstado()){
                cboUf.setSelectedItem(cboUf.getItemAt(i));
                break;
           }
               
        }
        cboCidade.removeAllItems();
        CidadeDao cd = new CidadeDao();
        ArrayList cidadeList = cd.findByEstado(c.getCidadeCliente().getEstado());
        for (int i = 0; i <cidadeList.size(); i++) {
            cboCidade.addItem(cidadeList.get(i));
        }
        for (int i = 0; i < cboCidade.getItemCount(); i++) {
           Cidade cidade = (Cidade)cboCidade.getItemAt(i);
           if(cidade.getCdCidade() == c.getCidadeCliente().getCdCidade()){
                cboCidade.setSelectedItem(cboCidade.getItemAt(i));
                break;
           }
        }
        txtEndereco.setText(c.getEndereco());
    }
    
    public static void campoObrigatorio(JTextField campo){
        campo.setBackground(Color.yellow);
        campo.setBorder(new LineBorder(Color.RED));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox cboCidade;
    private javax.swing.JComboBox cboSexo;
    private javax.swing.JComboBox cboUf;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblCep;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblNasc;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblRg;
    private javax.swing.JLabel lblRua;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblUf;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JFormattedTextField txtCep;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JFormattedTextField txtDtNasc;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtRg;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables

    
    private void atualizarCidade() {
        cboUf.setSelectedItem(cliente.getCidadeCliente().getEstado());
        cboCidade.setSelectedItem(cliente.getCidadeCliente());
    }
}
