package br.com.hardsoftware.mercearia.view;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import br.com.hardsoftware.mercearia.control.FornecedorControle;
import br.com.hardsoftware.mercearia.dao.CidadeDao;
import br.com.hardsoftware.mercearia.dao.EstadoDao;
import br.com.hardsoftware.mercearia.dao.FornecedorDao;
import br.com.hardsoftware.mercearia.model.Cidade;
import br.com.hardsoftware.mercearia.model.Fornecedor;
import br.com.hardsoftware.mercearia.model.Estado;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.border.LineBorder;

/**
 *
 * @author Erbert
 */
public class CadastroFornecedor extends javax.swing.JDialog {

    private CadastroFornecedor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        lblCadastroFornecedor = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        lblCnpj = new javax.swing.JLabel();
        javax.swing.text.MaskFormatter maskTel = null;
        try{
            maskTel= new javax.swing.text.MaskFormatter("(##)#####-####");

        }
        catch (java.text.ParseException exc) {}
        txtCelular = 
        new javax.swing.JFormattedTextField(maskTel);
        lblTelefone = new javax.swing.JLabel();
        javax.swing.text.MaskFormatter maskCel = null;
        try{
            maskCel= new javax.swing.text.MaskFormatter("(##)####-####");

        }
        catch (java.text.ParseException exc) {}
        txtTelefone = new javax.swing.JFormattedTextField(maskCel);
        lblCelular = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        javax.swing.text.MaskFormatter maskCpf = null;
        try{
            maskCpf= new javax.swing.text.MaskFormatter("##.###.###/####-##");

        }
        catch (java.text.ParseException exc) {}
        txtCnpj = new javax.swing.JFormattedTextField(maskCpf);
        lblObserva = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaObserva = new javax.swing.JTextArea();
        lblEntrega = new javax.swing.JLabel();
        cbEntrega = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        txtEndereco = new javax.swing.JTextField();
        cbUf = new javax.swing.JComboBox();
        EstadoDao ed = new EstadoDao();
        ArrayList estadoList = ed.findAll();
        for (int i = 0; i <estadoList.size(); i++) {
            cbUf.addItem(estadoList.get(i));
        }
        lblRua = new javax.swing.JLabel();
        lblUf = new javax.swing.JLabel();
        lblCep = new javax.swing.JLabel();
        javax.swing.text.MaskFormatter maskCEP = null; try{ maskCEP= new javax.swing.text.MaskFormatter("##.###-###"); maskCEP.setPlaceholderCharacter('_');  } catch (java.text.ParseException exc) {}
        txtCep = new javax.swing.JFormattedTextField(maskCEP);
        lblCidade = new javax.swing.JLabel();
        cbCidade = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Cliente");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/hardsoftware/mercearia/images/Icone Cliente - Ax54.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        lblCadastroFornecedor.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        lblCadastroFornecedor.setText("Cadastro de Fornecedor");

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        lblNome.setText("Nome completo:");

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        lblCnpj.setText("CNPJ:");

        txtCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCelularActionPerformed(evt);
            }
        });

        lblTelefone.setText("Telefone:");

        txtTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefoneActionPerformed(evt);
            }
        });

        lblCelular.setText("Celular:");

        lblEmail.setText("E-mail:");

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        lblObserva.setText("Observações:");

        txtAreaObserva.setColumns(20);
        txtAreaObserva.setRows(5);
        jScrollPane1.setViewportView(txtAreaObserva);

        lblEntrega.setText("Fornecedor Entrega:");

        cbEntrega.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Não", "Sim" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCelular))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTelefone)
                            .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmail)
                            .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblNome)
                                .addGap(142, 142, 142)
                                .addComponent(lblCnpj))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblObserva))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblEntrega, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel15)
                                    .addComponent(cbEntrega, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(lblCnpj))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefone)
                    .addComponent(lblCelular)
                    .addComponent(lblEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblObserva)
                    .addComponent(lblEntrega))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cbEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel15)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane3.addTab("Dados Pessoais", jPanel2);

        txtEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnderecoActionPerformed(evt);
            }
        });

        cbUf.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbUfItemStateChanged(evt);
            }
        });
        cbUf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbUfActionPerformed(evt);
            }
        });

        lblRua.setText("Endereço:");

        lblUf.setText("UF:");

        lblCep.setText("CEP:");

        txtCep.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCep.setToolTipText("Teste");
        txtCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCepActionPerformed(evt);
            }
        });

        lblCidade.setText("Cidade:");

        cbCidade.removeAllItems();
        CidadeDao cd = new CidadeDao();
        ArrayList cidadeList = cd.findByEstado((Estado) cbUf.getSelectedItem());
        for (int i = 0; i <cidadeList.size(); i++) {
            cbCidade.addItem(cidadeList.get(i));
        }
        cbCidade.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbCidadeItemStateChanged(evt);
            }
        });
        cbCidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbCidadeMouseClicked(evt);
            }
        });
        cbCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCidadeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCep)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lblUf)
                                .addGap(53, 53, 53))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(cbUf, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(3, 3, 3)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCidade)
                            .addComponent(cbCidade, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(lblRua)
                    .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(220, 220, 220))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCep)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUf)
                    .addComponent(lblCidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(lblRua)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        txtCep.getAccessibleContext().setAccessibleName("");
        txtCep.getAccessibleContext().setAccessibleDescription("");

        jTabbedPane3.addTab(" Endereço", jPanel3);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/hardsoftware/mercearia/images/print.png"))); // NOI18N
        jButton1.setText("Imprimir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblCadastroFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCadastroFornecedor)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnSalvar)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void FDtBatismoAguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FDtBatismoAguaActionPerformed
    }//GEN-LAST:event_FDtBatismoAguaActionPerformed

    private void CEleitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CEleitorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CEleitorActionPerformed

    private void FLocalBatismoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FLocalBatismoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FLocalBatismoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        //this.dispose();
        boolean vazio = false;
        boolean cnpjvalido = Fornecedor.validaCnpj(txtCnpj.getText());
        if(txtNome.getText().equals("")){
             CadastroFornecedor.campoObrigatorio(txtNome);
             vazio = true;
        }
        if(txtCnpj.getText().equals("  .   .   /    -  ")){
            CadastroFornecedor.campoObrigatorio(txtCnpj);
            vazio = true;
        }else{
            if(!cnpjvalido){
            campoObrigatorio(txtCnpj);
            JOptionPane.showMessageDialog(null, "CNPJ Inválido", "Erro - Dados Inválidos", JOptionPane.ERROR_MESSAGE);
            vazio = true;
            }
        }
        if(txtCelular.getText().equals("(  )     -    ")){
            CadastroFornecedor.campoObrigatorio(txtCelular);
            vazio = true;
        }
        if(txtTelefone.getText().equals("(  )    -    ")){
            CadastroFornecedor.campoObrigatorio(txtTelefone);
            vazio = true;
        }
        if(txtEmail.getText().equals("")){
            CadastroFornecedor.campoObrigatorio(txtEmail);
            vazio = true;
        }
        if(txtCep.getText().equals("__.___-___")){
            CadastroFornecedor.campoObrigatorio(txtCep);
            vazio = true;
        }
        if(txtEndereco.getText().equals("")){
            CadastroFornecedor.campoObrigatorio(txtEndereco);
            vazio = true;
        }
        if(vazio == false){
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Existem campos vazios", "Erro - Campo Vazio", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        cancel = true;
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void FDtDecisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FDtDecisaoActionPerformed

    }//GEN-LAST:event_FDtDecisaoActionPerformed

    private void FDtCasamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FDtCasamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FDtCasamentoActionPerformed

    private void FDtBatismoEspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FDtBatismoEspActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FDtBatismoEspActionPerformed

    private void CGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CGrupoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CGrupoActionPerformed

    private void CAdmissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CAdmissaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CAdmissaoActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void CCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CCargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CCargoActionPerformed

    private void txtCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCelularActionPerformed

    private void txtTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefoneActionPerformed

    private void FProfissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FProfissaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FProfissaoActionPerformed

    private void CEstCivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CEstCivilActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_CEstCivilActionPerformed

    private void CEstCivilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CEstCivilMouseClicked

    }//GEN-LAST:event_CEstCivilMouseClicked

    private void CEscolaridadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CEscolaridadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CEscolaridadeActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void CUFNaturalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CUFNaturalidadeActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_CUFNaturalidadeActionPerformed

    private void CNaturalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CNaturalidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CNaturalidadeActionPerformed

    private void FDtBatismoAguaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FDtBatismoAguaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_FDtBatismoAguaMouseClicked

    private void FDtBatismoAguaComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_FDtBatismoAguaComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_FDtBatismoAguaComponentShown

    private void CUFNaturalidadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CUFNaturalidadeMouseClicked
        // TODO add your handling code here:


    }//GEN-LAST:event_CUFNaturalidadeMouseClicked

    private void CCongBatismoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CCongBatismoActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_CCongBatismoActionPerformed

    private void CCongBatismoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CCongBatismoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CCongBatismoMouseClicked

    private void CUFNaturalidadeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CUFNaturalidadeItemStateChanged
    }//GEN-LAST:event_CUFNaturalidadeItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    }//GEN-LAST:event_jButton2ActionPerformed
    DefaultListModel listaGrupo = new DefaultListModel();
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FornecedorDao fo = new FornecedorDao();
        FornecedorControle.gerarHtml(fo.findByCnpj(txtCnpj.getText()));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCepActionPerformed

    private void cbUfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbUfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbUfActionPerformed

    private void txtEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnderecoActionPerformed

    private void cbCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCidadeActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cbCidadeActionPerformed

    private void cbCidadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbCidadeMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_cbCidadeMouseClicked

    private void cbCidadeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbCidadeItemStateChanged

    }//GEN-LAST:event_cbCidadeItemStateChanged

    private void cbUfItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbUfItemStateChanged
        cbCidade.removeAllItems();
        CidadeDao cd = new CidadeDao();
        ArrayList cidadeList = cd.findByEstado((Estado) cbUf.getSelectedItem());
        for (int i = 0; i < cidadeList.size(); i++) {
            cbCidade.addItem(cidadeList.get(i));
        }
    }//GEN-LAST:event_cbUfItemStateChanged

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    /**
     * @param args the command line arguments
     */
    private static CadastroFornecedor tela;

    public static CadastroFornecedor getInstance(java.awt.Frame parent, boolean modal) {
        if (tela == null) {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
             * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
             */
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(CadastroFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(CadastroFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(CadastroFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(CadastroFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>
            //</editor-fold>
            tela = new CadastroFornecedor(parent, modal);
            return tela;
        } else {
            return tela;
        }
    }

    public static void mostrar(Fornecedor f) {
        CadastroFornecedor dialog = CadastroFornecedor.getInstance(
                new javax.swing.JFrame(), true);
        dialog.prepararMostrar(f);
        dialog.setVisible(true);
        tela = null;

    }

    private static boolean cancel = false;

    public static Fornecedor editar(Fornecedor f) {
        CadastroFornecedor dialog = CadastroFornecedor.getInstance(
                new javax.swing.JFrame(), true);
        dialog.prepararEditar(f);
        dialog.setVisible(true);
        //Gambiarra
        if (CadastroFornecedor.cancel == true) {
            cancel = false;
            tela = null;
            return f;
        } else {
            f = dialog.getEstadoTela();
            tela = null;
            return f;
        }
    }
    
    public void cidade(String cnpj){
        FornecedorDao fu = new FornecedorDao();
        Fornecedor f = fu.findByCpf(cnpj);
        cbUf.setSelectedItem(f.getCidadeFornecedor().getEstado());
        cbCidade.setSelectedItem(f.getCidadeFornecedor());
    }

    public static Fornecedor inserir() {
        CadastroFornecedor dialog = CadastroFornecedor.getInstance(
                new javax.swing.JFrame(), true);

        dialog.setVisible(true);
        //Gambiarra
        if (CadastroFornecedor.cancel == true) {
            return null;
        } else {
            return dialog.getEstadoTela();
        }

    }

    public Fornecedor getEstadoTela() {
        Fornecedor f = new Fornecedor();
        f.setNmFornecedor(txtNome.getText());
        f.setCnpjFornecedor(txtCnpj.getText());
        f.setCelularFornecedor(txtCelular.getText());
        f.setTelefoneFornecedor(txtTelefone.getText());
        f.setObservFornecedor(txtAreaObserva.getText());
        boolean entrega = false;
        if (cbEntrega.getSelectedItem().equals("Não")) {
            entrega = false;
        } else if (cbEntrega.getSelectedItem().equals("Sim")) {
            entrega = true;
        }
        f.setEntregaFornecedor(entrega);
        f.setEmailFornecedor(txtEmail.getText());
        f.setCepFornecedor(txtCep.getText());
        f.setCidadeFornecedor((Cidade) cbCidade.getSelectedItem()); //Lembrando que ele envia o Objeto cidade, não só o nome
        f.setEnderecoFornecedor(txtEndereco.getText());
        return f;
    }

    public void prepararMostrar(Fornecedor f) {
        //Dando Enable para todos componentes pois só vou mostar imformações nessa parte
        txtNome.setEnabled(false);
        txtCnpj.setEnabled(false);
        txtCelular.setEnabled(false);
        txtTelefone.setEnabled(false);
        txtAreaObserva.setEnabled(false);
        cbEntrega.setEnabled(false);
        txtEmail.setEnabled(false);
        txtCep.setEnabled(false);
        cbCidade.setEnabled(false);
        cbUf.setEnabled(false);
        txtEndereco.setEnabled(false);
        btnSalvar.setVisible(false);
        btnCancelar.setVisible(false);
        //Setando as informações recebidas por parâmetro
        txtNome.setText(f.getNmFornecedor());
        txtCnpj.setText(f.getCnpjFornecedor());
        txtCelular.setText(f.getCelularFornecedor());
        txtTelefone.setText(f.getTelefoneFornecedor());
        txtAreaObserva.setText(f.getObservFornecedor());
        if (f.getEnderecoFornecedor() == "Não") {
            cbEntrega.setSelectedItem(false);
        } else if (f.getEnderecoFornecedor() == "Sim") {
            cbEntrega.setSelectedItem(true);
        }
        txtEmail.setText(f.getEmailFornecedor());
        txtCep.setText(f.getCepFornecedor());
        for (int i = 0; i < cbUf.getItemCount(); i++) {
           Estado uf = (Estado)cbUf.getItemAt(i);
           if(uf.getCodEstado() == f.getCidadeFornecedor().getEstado().getCodEstado()){
                cbUf.setSelectedItem(cbUf.getItemAt(i));
                break;
           }
        }
        cbCidade.removeAllItems();
        CidadeDao cd = new CidadeDao();
        ArrayList cidadeList = cd.findByEstado(f.getCidadeFornecedor().getEstado());
        for (int i = 0; i <cidadeList.size(); i++) {
            cbCidade.addItem(cidadeList.get(i));
        }
        for (int i = 0; i < cbCidade.getItemCount(); i++) {
           Cidade cidade = (Cidade)cbCidade.getItemAt(i);
           if(cidade.getCdCidade() == f.getCidadeFornecedor().getCdCidade()){
                cbCidade.setSelectedItem(cbCidade.getItemAt(i));
                break;
           }
        }
        
        txtEndereco.setText(f.getEnderecoFornecedor());
    }

    public void prepararEditar(Fornecedor c) {
        //Setando as informações recebidas por parâmetro

        txtNome.setText(c.getNmFornecedor());
        txtCnpj.setText(c.getCnpjFornecedor());
        txtCelular.setText(c.getCelularFornecedor());
        txtTelefone.setText(c.getTelefoneFornecedor());
        txtAreaObserva.setText(c.getObservFornecedor());
        if (c.getEnderecoFornecedor() == "Não") {
            cbEntrega.setSelectedItem(false);
        } else if (c.getEnderecoFornecedor() == "Sim") {
            cbEntrega.setSelectedItem(true);
        }
        txtEmail.setText(c.getEmailFornecedor());
        txtCep.setText(c.getCepFornecedor());
        for (int i = 0; i < cbUf.getItemCount(); i++) {
           Estado uf = (Estado)cbUf.getItemAt(i);
           if(uf.getCodEstado() == c.getCidadeFornecedor().getEstado().getCodEstado()){
                cbUf.setSelectedItem(cbUf.getItemAt(i));
                break;
           }
               
        }
        cbCidade.removeAllItems();
        CidadeDao cd = new CidadeDao();
        ArrayList cidadeList = cd.findByEstado(c.getCidadeFornecedor().getEstado());
        for (int i = 0; i <cidadeList.size(); i++) {
            cbCidade.addItem(cidadeList.get(i));
        }
        for (int i = 0; i < cbCidade.getItemCount(); i++) {
           Cidade cidade = (Cidade)cbCidade.getItemAt(i);
           if(cidade.getCdCidade() == c.getCidadeFornecedor().getCdCidade()){
                cbCidade.setSelectedItem(cbCidade.getItemAt(i));
                break;
           }
        }
        txtEndereco.setText(c.getEnderecoFornecedor());
    }
    
    public static void campoObrigatorio(JTextField campo){
        campo.setBackground(Color.yellow);
        campo.setBorder(new LineBorder(Color.RED));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox cbCidade;
    private javax.swing.JComboBox cbEntrega;
    private javax.swing.JComboBox cbUf;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JLabel lblCadastroFornecedor;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblCep;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblCnpj;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEntrega;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblObserva;
    private javax.swing.JLabel lblRua;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblUf;
    private javax.swing.JTextArea txtAreaObserva;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JFormattedTextField txtCep;
    private javax.swing.JTextField txtCnpj;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
