package br.com.hardsoftware.mercearia.view;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */





import br.com.hardsoftware.mercearia.control.ProdutoControle;
import br.com.hardsoftware.mercearia.dao.CategoriaDao;
import br.com.hardsoftware.mercearia.dao.ProdutoDao;
import br.com.hardsoftware.mercearia.dao.UnidadeProdutoDao;
import br.com.hardsoftware.mercearia.model.Categoria;
import br.com.hardsoftware.mercearia.model.Produto;
import br.com.hardsoftware.mercearia.model.UnidadeProduto;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;


/**
 *
 * @author Alysson
 */
public class CadastroProduto extends javax.swing.JDialog {

    private  Produto getEstadoTela() {
        Produto p = new Produto();
        p.setUnidadeProduto((UnidadeProduto) cboUnidade.getSelectedItem());
        p.setCategoria((Categoria) cboCategoria.getSelectedItem());
        p.setCodigoBarraProduto(txtCod.getText());
        p.setDescricaoProduto(txtDescricao.getText());
        p.setMarcaProduto(txtMarca.getText());
        p.setNmProduto(txtNome.getText());
        p.setPrecoProduto(Double.parseDouble(txtPreco.getText().replace(",", ".")));
        p.setQtdProduto(Integer.parseInt(txtQuant.getText()));
        p.setValorProduto(Double.parseDouble(txtValor.getText().replace(",", ".")));
        return p;
    }

    private CadastroProduto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblNasc = new javax.swing.JLabel();
        lblSexo = new javax.swing.JLabel();
        cboCategoria = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        lblCpf = new javax.swing.JLabel();
        lblCelular = new javax.swing.JLabel();
        txtCod = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        txtPreco = new javax.swing.JTextField();
        lblCelular1 = new javax.swing.JLabel();
        txtQuant = new javax.swing.JTextField();
        lblSexo1 = new javax.swing.JLabel();
        cboUnidade = new javax.swing.JComboBox();
        UnidadeProdutoDao ud = new UnidadeProdutoDao();
        ArrayList arrayUnidade = ud.findAll();
        for (int i = 0; i < arrayUnidade.size(); i++) {
            cboUnidade.addItem(arrayUnidade.get(i));
        }
        lblSexo2 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescricao = new javax.swing.JTextArea();
        lblCelular2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Produtos");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/hardsoftware/mercearia/images/Icone Produto - Ax54.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jLabel2.setText("Cadastro de Produtos");

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        lblNome.setText("Nome do Produto:");

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        lblNasc.setText("Marca:");

        lblSexo.setText("Categoria:");

        CategoriaDao cd = new CategoriaDao();         ArrayList arrayCategoria = cd.findAll();         for (int i = 0; i < arrayCategoria.size(); i++) {             cboCategoria.addItem(arrayCategoria.get(i));         }
        cboCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCategoriaActionPerformed(evt);
            }
        });

        lblCpf.setText("Código de Barras:");

        lblCelular.setText("Preço:");

        lblCelular1.setText("Quantidade:");

        lblSexo1.setText("Unidade:");

        cboUnidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboUnidadeActionPerformed(evt);
            }
        });

        lblSexo2.setText("Valor da Unidade:");

        txtDescricao.setColumns(20);
        txtDescricao.setRows(5);
        jScrollPane1.setViewportView(txtDescricao);

        lblCelular2.setText("Descrição:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblNome))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblCpf)
                                .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblNasc)
                                .addComponent(txtMarca, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(1, 1, 1)
                                    .addComponent(lblSexo))
                                .addComponent(cboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblCelular)
                                .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblCelular1)
                                .addComponent(jLabel15)
                                .addComponent(txtQuant))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblSexo2)
                                .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblSexo1)
                                .addComponent(cboUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(8, 8, 8)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCelular2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(lblCpf)
                    .addComponent(lblNasc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblSexo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtQuant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCelular)
                        .addComponent(lblCelular1)
                        .addComponent(lblSexo2)
                        .addComponent(lblSexo1)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel15)
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCelular2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jTabbedPane3.addTab("Dados do Produto", jPanel2);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/hardsoftware/mercearia/images/print.png"))); // NOI18N
        jButton1.setText("Imprimir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnSalvar)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void FDtBatismoAguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FDtBatismoAguaActionPerformed
    }//GEN-LAST:event_FDtBatismoAguaActionPerformed

    private void CEleitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CEleitorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CEleitorActionPerformed

    private void FLocalBatismoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FLocalBatismoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FLocalBatismoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        
        boolean vazio = false;
        if(txtNome.getText().equals("")){
            CadastroCliente.campoObrigatorio(txtNome);
            vazio = true;
        }
        if(txtCod.getText().equals("")){
            CadastroCliente.campoObrigatorio(txtCod);
            vazio = true;
        }
        if(txtMarca.getText().equals("")){
            CadastroCliente.campoObrigatorio(txtMarca);
            vazio = true;
        }
        if(txtPreco.getText().equals("")){
            CadastroCliente.campoObrigatorio(txtPreco);
            vazio = true;
        }
        if(txtQuant.getText().equals("")){
            CadastroCliente.campoObrigatorio(txtQuant);
            vazio = true;
        }
        if(txtValor.getText().equals("")){
            CadastroCliente.campoObrigatorio(txtValor);
            vazio = true;
        }
        if(!vazio){
            this.dispose();
        }
        else{
             JOptionPane.showMessageDialog(null, "Existem campos vazios", "Erro - Campo Vazio", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        CadastroCliente.cancel = true;
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void FDtDecisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FDtDecisaoActionPerformed


    }//GEN-LAST:event_FDtDecisaoActionPerformed

    private void FDtCasamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FDtCasamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FDtCasamentoActionPerformed

    private void FDtBatismoEspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FDtBatismoEspActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FDtBatismoEspActionPerformed

    private void CGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CGrupoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CGrupoActionPerformed

    private void CAdmissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CAdmissaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CAdmissaoActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void CCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CCargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CCargoActionPerformed

    private void FProfissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FProfissaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FProfissaoActionPerformed

    private void CEstCivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CEstCivilActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_CEstCivilActionPerformed

    private void CEstCivilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CEstCivilMouseClicked

    }//GEN-LAST:event_CEstCivilMouseClicked

    private void CEscolaridadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CEscolaridadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CEscolaridadeActionPerformed

    private void CUFNaturalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CUFNaturalidadeActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_CUFNaturalidadeActionPerformed

    private void CNaturalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CNaturalidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CNaturalidadeActionPerformed

    private void FDtBatismoAguaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FDtBatismoAguaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_FDtBatismoAguaMouseClicked

    private void FDtBatismoAguaComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_FDtBatismoAguaComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_FDtBatismoAguaComponentShown

    private void CUFNaturalidadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CUFNaturalidadeMouseClicked
        // TODO add your handling code here:


    }//GEN-LAST:event_CUFNaturalidadeMouseClicked

    private void CCongBatismoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CCongBatismoActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_CCongBatismoActionPerformed

    private void CCongBatismoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CCongBatismoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CCongBatismoMouseClicked

    private void CUFNaturalidadeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CUFNaturalidadeItemStateChanged
    }//GEN-LAST:event_CUFNaturalidadeItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    }//GEN-LAST:event_jButton2ActionPerformed
    DefaultListModel listaGrupo = new DefaultListModel();
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ProdutoDao pd = new ProdutoDao();
        ProdutoControle.gerarHtml(pd.findByCodBarras(txtCod.getText()));

    }//GEN-LAST:event_jButton1ActionPerformed

    private void cboUnidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboUnidadeActionPerformed

    }//GEN-LAST:event_cboUnidadeActionPerformed

    private void cboCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCategoriaActionPerformed
        
    }//GEN-LAST:event_cboCategoriaActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    /**
     * @param args the command line arguments
     */
    
   
    private static boolean cancel = false;
    public static Produto inserir() {
        CadastroProduto dialog = CadastroProduto.getInstance(
                                new javax.swing.JFrame(), true);
        
        dialog.setVisible(true);
            if(CadastroCliente.cancel == true){
                tela = null;
                return null;
            }
            else{
                Produto pro = dialog.getEstadoTela();
                tela = null;
                return pro;
            }
    }
    
        public static Produto alterar(Produto p) {
            CadastroProduto dialog = CadastroProduto.getInstance(
                                    new javax.swing.JFrame(), true);
        
            dialog.prepararEditar(p);
            dialog.setVisible(true);
            //Gambiarra
           if(CadastroCliente.cancel == true){
                tela = null;
                return null;
            }
            else{
                Produto pro = dialog.getEstadoTela();
                tela = null;
                return pro;
            }
        }
        public static Produto mostrar(Produto p) {
            CadastroProduto dialog = CadastroProduto.getInstance(
                                    new javax.swing.JFrame(), true);
            
            dialog.prepararMostrar(p);
            dialog.setVisible(true);
            
            //Gambiarra
            if(CadastroCliente.cancel == true){
                tela = null;
                return null;
            }
            else{
                Produto pro = dialog.getEstadoTela();
                tela = null;
                return pro;
            }
        }
        

    private static CadastroProduto tela;    
    
    public static CadastroProduto getInstance(java.awt.Frame parent, boolean modal) {        
        if (tela == null){
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
             * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
             */
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>
        
            //</editor-fold>
            tela = new CadastroProduto(parent, modal);  
            return tela;
        }
        else{
            return tela;
        }
    }
    
    public void prepararMostrar(Produto p){
        cboCategoria.setSelectedItem(p.getCategoria());
        cboUnidade.setSelectedItem(p.getUnidadeProduto());
        txtCod.setText(p.getCodigoBarraProduto()+"");
        txtDescricao.setText(p.getDescricaoProduto());
        txtMarca.setText(p.getMarcaProduto());
        txtNome.setText(p.getNmProduto());
        txtPreco.setText(p.getPrecoProduto()+"");
        txtQuant.setText(p.getQtdProduto()+"");
        txtValor.setText(p.getValorProduto() + "");
        
        txtValor.setEnabled(false);
        txtQuant.setEnabled(false);
        txtPreco.setEnabled(false);
        txtNome.setEnabled(false);
        txtMarca.setEnabled(false);
        txtDescricao.setEnabled(false);
        txtCod.setEnabled(false);
        cboUnidade.setEnabled(false);
        cboCategoria.setEnabled(false);
        btnSalvar.setText("OK");
        btnCancelar.setVisible(false);
    }
    
    public void prepararEditar(Produto p) {
        //Setando as informações recebidas por parâmetro
        
        cboCategoria.setSelectedItem(p.getCategoria());
        cboUnidade.setSelectedItem(p.getUnidadeProduto());
        txtCod.setText(p.getCodigoBarraProduto()+"");
        txtDescricao.setText(p.getDescricaoProduto());
        txtMarca.setText(p.getMarcaProduto());
        txtNome.setText(p.getNmProduto());
        txtPreco.setText(p.getPrecoProduto()+"");
        txtQuant.setText(p.getQtdProduto()+"");
        txtValor.setText(p.getValorProduto() + "");
        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox cboCategoria;
    private javax.swing.JComboBox cboUnidade;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblCelular1;
    private javax.swing.JLabel lblCelular2;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblNasc;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblSexo1;
    private javax.swing.JLabel lblSexo2;
    private javax.swing.JTextField txtCod;
    private javax.swing.JTextArea txtDescricao;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtQuant;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
