/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.hardsoftware.mercearia.view;

import br.com.hardsoftware.mercearia.dao.CategoriaDao;
import br.com.hardsoftware.mercearia.dao.UnidadeProdutoDao;
import br.com.hardsoftware.mercearia.model.Categoria;
import br.com.hardsoftware.mercearia.model.UnidadeProduto;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alyssonkelvim
 */
public class GerenciaProdutoConfig extends javax.swing.JDialog {

    /**
     * Creates new form GerenciaProdutoAvancado
     */
     private GerenciaProdutoConfig(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    ModeloTabelaCategoria modelCategoria = new ModeloTabelaCategoria();
    DefaultTableModel model = modelCategoria.findAll();
    ModeloTabelaUnidade modelUnidade = new ModeloTabelaUnidade();
    DefaultTableModel modelU = modelUnidade.findAll();
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtCategoria = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCategoria = new javax.swing.JTable();
        btnCategoria = new javax.swing.JButton();
        btnCategoriaExc = new javax.swing.JButton();
        Panel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtUnidade = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblUnidade = new javax.swing.JTable();
        btnUnidade = new javax.swing.JButton();
        btnUnidadeExc = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/hardsoftware/mercearia/images/Icone Produto - Ax54.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jLabel2.setText("Configurações de Produto");

        jLabel3.setText("Categoria:");

        txtCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCategoriaActionPerformed(evt);
            }
        });

        tblCategoria.setModel(model);
        tblCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCategoriaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCategoria);

        btnCategoria.setText("Salvar");
        btnCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoriaActionPerformed(evt);
            }
        });

        btnCategoriaExc.setText("Excluir");
        btnCategoriaExc.setEnabled(false);
        btnCategoriaExc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoriaExcActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCategoriaExc, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCategoria)
                    .addComponent(btnCategoriaExc))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Categorias", jPanel2);

        jLabel4.setText("Unidade");

        txtUnidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnidadeActionPerformed(evt);
            }
        });

        tblUnidade.setModel(modelU);
        tblUnidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUnidadeMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblUnidade);

        btnUnidade.setText("Salvar");
        btnUnidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnidadeActionPerformed(evt);
            }
        });

        btnUnidadeExc.setText("Excluir");
        btnUnidadeExc.setEnabled(false);
        btnUnidadeExc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnidadeExcActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                        .addComponent(btnUnidadeExc, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUnidade)
                    .addComponent(btnUnidadeExc))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Unidades", Panel);

        btnCancelar.setText("Sair");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar)
                .addGap(5, 5, 5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCategoriaActionPerformed

    private void btnCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoriaActionPerformed
        // TODO add your handling code here:
        if(btnCategoria.getText().equals("Alterar")){
            
            int row = tblCategoria.getSelectedRow();
            Categoria c = (Categoria) tblCategoria.getValueAt(row, 1);
            c.setNmCategoria(txtCategoria.getText());
            c.setDescricaoCategoria("");
            CategoriaDao cd = new CategoriaDao();
            cd.alter(c);
            Atualizar();
            txtCategoria.setText("");
            btnCategoria.setText("Salvar");
            btnCategoriaExc.setEnabled(false);
        }else{
            Categoria c= new Categoria();
            c.setNmCategoria(txtCategoria.getText());
            c.setDescricaoCategoria("");
            CategoriaDao cd = new CategoriaDao();
            cd.insert(c);
            Atualizar();
        }
    }//GEN-LAST:event_btnCategoriaActionPerformed

    private void txtUnidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnidadeActionPerformed

    private void tblCategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCategoriaMouseClicked
        // TODO add your handling code here:
        int row = tblCategoria.getSelectedRow();
        String edit = tblCategoria.getValueAt(row, 1).toString();
        txtCategoria.setText(edit);
        btnCategoria.setText("Alterar");
        btnCategoriaExc.setEnabled(true);
    }//GEN-LAST:event_tblCategoriaMouseClicked

    private void btnCategoriaExcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoriaExcActionPerformed
        // TODO add your handling code here: 
        int row = tblCategoria.getSelectedRow();
        Categoria cat = (Categoria) tblCategoria.getValueAt(row, 1);
        CategoriaDao cd = new CategoriaDao();
        cd.delete(cat);
        Atualizar();
        txtCategoria.setText("");
        btnCategoria.setText("Salvar");
        btnCategoriaExc.setEnabled(false);
    }//GEN-LAST:event_btnCategoriaExcActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnUnidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnidadeActionPerformed
        // TODO add your handling code here:
        if(btnUnidade.getText().equals("Alterar")){
            
            int row = tblUnidade.getSelectedRow();
            UnidadeProduto u = (UnidadeProduto) tblUnidade.getValueAt(row, 1);
            u.setDescricaoUnidade(txtUnidade.getText());
            UnidadeProdutoDao ud = new UnidadeProdutoDao();
            ud.alter(u);
            AtualizarU();
            txtCategoria.setText("");
            btnCategoria.setText("Salvar");
            btnCategoriaExc.setEnabled(false);
        }else{
            UnidadeProduto u = new UnidadeProduto();
            u.setDescricaoUnidade(txtUnidade.getText());
            UnidadeProdutoDao ud = new UnidadeProdutoDao();
            ud.insert(u);
            AtualizarU();
        }
    }//GEN-LAST:event_btnUnidadeActionPerformed

    private void btnUnidadeExcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnidadeExcActionPerformed
        // TODO add your handling code here:
         int row = tblUnidade.getSelectedRow();
        UnidadeProduto u = (UnidadeProduto) tblUnidade.getValueAt(row, 1);
        UnidadeProdutoDao ud = new UnidadeProdutoDao();
        ud.delete(u);
        AtualizarU();
        txtUnidade.setText("");
        btnUnidade.setText("Salvar");
        btnUnidadeExc.setEnabled(false);
    }//GEN-LAST:event_btnUnidadeExcActionPerformed

    private void tblUnidadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUnidadeMouseClicked
        // TODO add your handling code here:
        // TODO add your handling code here:
        int row = tblUnidade.getSelectedRow();
        String edit = tblUnidade.getValueAt(row, 1).toString();
        txtUnidade.setText(edit);
        btnUnidade.setText("Alterar");
        btnUnidadeExc.setEnabled(true);
    }//GEN-LAST:event_tblUnidadeMouseClicked

    /**
     * @param args the command line arguments
     */
    private static GerenciaProdutoConfig tela;
    public static GerenciaProdutoConfig getInstance(java.awt.Frame parent, boolean modal) {        
        if (tela == null){
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
             * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
             */
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(GerenciaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(GerenciaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(GerenciaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(GerenciaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>
            return new GerenciaProdutoConfig(parent, modal);        
        }
        else{
            return tela;
        }
    }
     
    public static void iniciar() {
       GerenciaProdutoConfig dialog = GerenciaProdutoConfig.getInstance(
                                new javax.swing.JFrame(), true);
        dialog.setVisible(true);

    }    
     public void Atualizar(){
            model = modelCategoria.findAll();
            tblCategoria.setModel(model);
            this.repaint();
    }
     public void AtualizarU(){
            modelU = modelUnidade.findAll();
            tblUnidade.setModel(modelU);
            this.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCategoria;
    private javax.swing.JButton btnCategoriaExc;
    private javax.swing.JButton btnUnidade;
    private javax.swing.JButton btnUnidadeExc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblCategoria;
    private javax.swing.JTable tblUnidade;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtUnidade;
    // End of variables declaration//GEN-END:variables
}
