/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.hardsoftware.mercearia.view;

import br.com.hardsoftware.mercearia.control.CaixaControle;
import br.com.hardsoftware.mercearia.control.LoginControle;
import br.com.hardsoftware.mercearia.dao.CaixaDao;
import br.com.hardsoftware.mercearia.model.Caixa;
import br.com.hardsoftware.mercearia.model.Funcionario;
import br.com.hardsoftware.mercearia.model.Venda;
import br.com.hardsoftware.mercearia.relatorios.Html;
import java.awt.Window;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alysson
 */
public class TelaCaixa extends javax.swing.JFrame {

    /**
     * Creates new form Venda
     */
    
    private void fechar(){
        if(CaixaControle.getStatus().equals("Aberto")){
            JOptionPane.showMessageDialog(null, "Feche o caixa primeiro!", "Caixa Aberto", JOptionPane.INFORMATION_MESSAGE);
        }else{
            tela = null;
            this.dispose();
        }
    }
    private TelaCaixa(java.awt.Frame parent, boolean modal) {
        initComponents();
        this.setExtendedState(6);
        atualizarTotal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    ModeloTabelaVenda modeloVenda= new ModeloTabelaVenda();
    DefaultTableModel modelVenda = modeloVenda.iniciar();
    ModeloTabelaCaixa modeloCaixa = new ModeloTabelaCaixa();
    DefaultTableModel modelCaixa = modeloCaixa.findAll();
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnRelatorio = new javax.swing.JButton();
        btnBloquear = new javax.swing.JButton();
        btnAbrir = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        btnIniciarVenda = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaCaixa = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaVenda = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        btnCancelarVenda = new javax.swing.JButton();
        btnDetalhesVenda = new javax.swing.JButton();

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/hardsoftware/mercearia/images/Icone Produto - Ax54.png"))); // NOI18N
        jLabel2.setText("jLabel1");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jLabel5.setText("Gerência de Produto");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel1.setText("Caixas");

        txtTotal.setEditable(false);
        txtTotal.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        txtTotal.setForeground(new java.awt.Color(0, 0, 102));
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 102));
        jLabel10.setText("Total de Vendas:");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/hardsoftware/mercearia/images/caixa/Caixa - Icone.png"))); // NOI18N
        jLabel6.setText("jLabel1");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jLabel7.setText("Controle de Caixa - Mercearia do Toninho");

        btnRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/hardsoftware/mercearia/images/caixa/Caixa - Relatório.png"))); // NOI18N
        btnRelatorio.setText("Relatório");
        btnRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioActionPerformed(evt);
            }
        });

        btnBloquear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/hardsoftware/mercearia/images/caixa/Caixa - Bloquear.png"))); // NOI18N
        btnBloquear.setText("Bloquear Caixa");
        btnBloquear.setEnabled(false);
        btnBloquear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBloquearActionPerformed(evt);
            }
        });

        btnAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/hardsoftware/mercearia/images/caixa/Caixa - Abertura.png"))); // NOI18N
        btnAbrir.setText("Abrir Caixa");
        btnAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirActionPerformed(evt);
            }
        });

        btnFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/hardsoftware/mercearia/images/caixa/Caixa - Fechamento.png"))); // NOI18N
        btnFechar.setText("Fechar Caixa");
        btnFechar.setEnabled(false);
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/hardsoftware/mercearia/images/caixa/Caixa - Sair.png"))); // NOI18N
        jButton6.setText("Sair");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        btnIniciarVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/hardsoftware/mercearia/images/caixa/Caixa - Iniciar Venda.png"))); // NOI18N
        btnIniciarVenda.setText("Iniciar Venda");
        btnIniciarVenda.setEnabled(false);
        btnIniciarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarVendaActionPerformed(evt);
            }
        });

        tabelaCaixa.setModel(modelCaixa);
        tabelaCaixa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaCaixaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelaCaixa);

        tabelaVenda.setModel(modelVenda);
        tabelaVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaVendaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabelaVenda);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel3.setText("Vendas");

        btnCancelarVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/hardsoftware/mercearia/images/caixa/Caixa - Fechar Venda.png"))); // NOI18N
        btnCancelarVenda.setText("Cancelar Venda");
        btnCancelarVenda.setEnabled(false);

        btnDetalhesVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/hardsoftware/mercearia/images/caixa/Caixa - Detalhes.png"))); // NOI18N
        btnDetalhesVenda.setText("Detalhes");
        btnDetalhesVenda.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(448, 448, 448)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAbrir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFechar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRelatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBloquear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTotal)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnIniciarVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancelarVenda)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnDetalhesVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnIniciarVenda)
                            .addComponent(btnCancelarVenda)
                            .addComponent(btnDetalhesVenda))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAbrir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBloquear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnFechar.getAccessibleContext().setAccessibleDescription("");
        btnCancelarVenda.getAccessibleContext().setAccessibleName("Fechar Venda");
        btnCancelarVenda.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        fechar();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btnBloquearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBloquearActionPerformed
        // TODO add your handling code here:
        this.setEnabled(false);
        TelaBloqueio.iniciar();
    }//GEN-LAST:event_btnBloquearActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        // TODO add your handling code here:
        ArrayList<Venda> v = new ArrayList();
        for (int i = 0; i < tabelaVenda.getRowCount(); i++) {
            Venda venda = (Venda) tabelaVenda.getValueAt(i, 0);
            v.add(venda);
        }
        CaixaControle.fecharCaixa(v);
        modelVenda = modeloVenda.limpar(modelVenda);
        tabelaVenda.setModel(modelVenda);
        modelCaixa = modeloCaixa.findAll();
        tabelaCaixa.setModel(modelCaixa);
        btnIniciarVenda.setEnabled(false);
        btnAbrir.setEnabled(true);
        btnFechar.setEnabled(false);
        btnBloquear.setEnabled(false);
        this.repaint();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirActionPerformed
        // TODO add your handling code here:
        Funcionario f = LoginControle.getFuncOnline();
        Calendar c  = CaixaControle.abrirCaixa(f);
        modelCaixa = modeloCaixa.findAllAndNow(c, f);
        tabelaCaixa.setModel(modelCaixa);
        modelVenda = modeloVenda.limpar(modelVenda);
        tabelaVenda.setModel(modelVenda);
        btnAbrir.setEnabled(false);
        btnBloquear.setEnabled(true);
        btnFechar.setEnabled(true);
        tabelaVenda.setEnabled(true);
        tabelaCaixa.setEnabled(true);
        btnIniciarVenda.setEnabled(true);
        this.repaint();
    }//GEN-LAST:event_btnAbrirActionPerformed

    private void tabelaVendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaVendaMouseClicked
        // TODO add your handling code here:
        btnDetalhesVenda.setEnabled(true);
        btnCancelarVenda.setEnabled(true);
    }//GEN-LAST:event_tabelaVendaMouseClicked

    private void btnIniciarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarVendaActionPerformed
        // TODO add your handling code here:
        CaixaControle.abrirVenda();
    }//GEN-LAST:event_btnIniciarVendaActionPerformed

    private void tabelaCaixaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaCaixaMouseClicked
        // TODO add your handling code here:
        if(tabelaCaixa.isEnabled()){
            int linha = tabelaCaixa.getSelectedRow();
            Caixa c = (Caixa) tabelaCaixa.getValueAt(linha, 1);
            modelVenda = modeloVenda.findByCaixa(c);
            tabelaVenda.setModel(modelVenda);
            this.repaint();
        }
    }//GEN-LAST:event_tabelaCaixaMouseClicked

    private void btnRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioActionPerformed
        // TODO add your handling code here:
        CaixaDao cd = new CaixaDao();        
        ArrayList<Caixa> listaCaixa = cd.findAll();
        CaixaControle.gerarHtml(listaCaixa);
    }//GEN-LAST:event_btnRelatorioActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    private static TelaCaixa tela;
    public static TelaCaixa getTela(){
        return tela;
    }
    public static TelaCaixa getInstance(java.awt.Frame parent, boolean modal) {        
        if (tela == null){
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
             * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
             */
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(GerenciaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(GerenciaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(GerenciaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(GerenciaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>
            tela = new TelaCaixa(parent, modal);
            return tela;        
        }
        else{
            
            return tela;
        }
    }
     
    public static void iniciar() {
       TelaCaixa dialog = TelaCaixa.getInstance(
                                new javax.swing.JFrame(), true);
        dialog.setVisible(true);

    }
    public static void Atualizar(){
        tela.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrir;
    private javax.swing.JButton btnBloquear;
    private javax.swing.JButton btnCancelarVenda;
    private javax.swing.JButton btnDetalhesVenda;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnIniciarVenda;
    private javax.swing.JButton btnRelatorio;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tabelaCaixa;
    private javax.swing.JTable tabelaVenda;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables

    private void atualizarTotal() {
        double soma = 0;
        for (int i = 0; i < tabelaVenda.getRowCount(); i++) {
            soma += Double.valueOf(tabelaVenda.getValueAt(i, 2).toString());
        }
        
        txtTotal.setText("R$ " + soma);
    }
    
    public static void addVenda(Venda v){
        tela.modelVenda = tela.modeloVenda.addVenda(v, tela.modelVenda);
        tela.tabelaVenda.setModel(tela.modelVenda);
        tela.atualizarTotal();
        tela.repaint();
    }

    
}
