/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.hardsoftware.mercearia.view;

import br.com.hardsoftware.mercearia.control.TelaPrincipalControler;
import br.com.hardsoftware.mercearia.model.Funcionario;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Erbert
 */
public class TelaPrincipal extends javax.swing.JFrame {

    

    /**
     * Creates new form TelaPrincipal
     */
    ModeloTabelaProdutoFaltando modelFaltando = new ModeloTabelaProdutoFaltando();
    DefaultTableModel model = modelFaltando.findAll();
    
    DefaultListModel lista = ModeloListaFaltando.listar();
    
    private TelaPrincipal(java.awt.Frame parent, boolean modal) {
        initComponents();
        setExtendedState(6);
        URL url = this.getClass().getResource("Icon.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(iconeTitulo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVendas = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnCliente = new javax.swing.JButton();
        btnFornecedor = new javax.swing.JButton();
        btnFuncionario = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaFaltando = new javax.swing.JTable();
        btnFornecedor1 = new javax.swing.JButton();
        principal = new javax.swing.JMenuBar();
        dados = new javax.swing.JMenu();
        cliente = new javax.swing.JMenuItem();
        funcionario = new javax.swing.JMenuItem();
        fornecedor = new javax.swing.JMenuItem();
        vendas = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        relatorio = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/hardsoftware/mercearia/images/principal/Icone Venda - Ax45.png"))); // NOI18N
        btnVendas.setText("Vendas");
        btnVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendasActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/hardsoftware/mercearia/images/principal/Icone Produto - Ax45.png"))); // NOI18N
        jButton2.setText("Produtos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/hardsoftware/mercearia/images/principal/Icone Cliente - Ax45.png"))); // NOI18N
        btnCliente.setText("Clientes");
        btnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteActionPerformed(evt);
            }
        });

        btnFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/hardsoftware/mercearia/images/principal/Icone Fornecedor- Ax45.png"))); // NOI18N
        btnFornecedor.setText("Fornecedor");
        btnFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFornecedorActionPerformed(evt);
            }
        });

        btnFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/hardsoftware/mercearia/images/principal/Icone Funcionario - Ax45.png"))); // NOI18N
        btnFuncionario.setText("Funcionários");
        btnFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFuncionarioActionPerformed(evt);
            }
        });

        jLabel1.setText("Produtos esgotando em estoque:");

        tabelaFaltando.setModel(model);
        jScrollPane2.setViewportView(tabelaFaltando);

        btnFornecedor1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/hardsoftware/mercearia/images/principal/logout.png"))); // NOI18N
        btnFornecedor1.setText("Sair");
        btnFornecedor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFornecedor1ActionPerformed(evt);
            }
        });

        dados.setText("Principal");

        cliente.setText("Clientes");
        cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteActionPerformed(evt);
            }
        });
        dados.add(cliente);

        funcionario.setText("Funcionário");
        funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funcionarioActionPerformed(evt);
            }
        });
        dados.add(funcionario);

        fornecedor.setText("Fornecedor");
        fornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fornecedorActionPerformed(evt);
            }
        });
        dados.add(fornecedor);

        vendas.setText("Vendas");
        vendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendasActionPerformed(evt);
            }
        });
        dados.add(vendas);

        jMenuItem1.setText("Produtos");
        jMenuItem1.setToolTipText("");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        dados.add(jMenuItem1);

        principal.add(dados);

        relatorio.setText("Relatórios");

        jMenuItem5.setText("Clientes");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        relatorio.add(jMenuItem5);

        jMenuItem6.setText("Funcionário");
        relatorio.add(jMenuItem6);

        jMenuItem7.setText("Fornecedor");
        relatorio.add(jMenuItem7);

        jMenuItem8.setText("Vendas");
        relatorio.add(jMenuItem8);

        principal.add(relatorio);

        setJMenuBar(principal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFuncionario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFornecedor)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(btnFornecedor1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnFornecedor)
                        .addComponent(btnFuncionario)
                        .addComponent(btnFornecedor1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnVendas)
                        .addComponent(jButton2))
                    .addComponent(btnCliente))
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(344, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void fornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fornecedorActionPerformed
        TelaPrincipalControler.iniciarFornecedor();
        
    }//GEN-LAST:event_fornecedorActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteActionPerformed
        TelaPrincipalControler.iniciarCliente();
    }//GEN-LAST:event_clienteActionPerformed

    private void funcionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funcionarioActionPerformed
        TelaPrincipalControler.iniciarFuncionario();
    }//GEN-LAST:event_funcionarioActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        TelaPrincipalControler.iniciarProduto();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFuncionarioActionPerformed
        // TODO add your handling code here:
        TelaPrincipalControler.iniciarFuncionario();
    }//GEN-LAST:event_btnFuncionarioActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        TelaPrincipalControler.iniciarProduto();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendasActionPerformed
        // TODO add your handling code here:
        TelaCaixa.iniciar();
    }//GEN-LAST:event_btnVendasActionPerformed

    private void btnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteActionPerformed
        // TODO add your handling code here:
        TelaPrincipalControler.iniciarCliente();
    }//GEN-LAST:event_btnClienteActionPerformed

    private void btnFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFornecedorActionPerformed
        // TODO add your handling code here:
        TelaPrincipalControler.iniciarFornecedor();
    }//GEN-LAST:event_btnFornecedorActionPerformed

    private void vendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vendasActionPerformed

    private void btnFornecedor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFornecedor1ActionPerformed
        // TODO add your handling code here:
        int opc =JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair?", "Sair", JOptionPane.YES_NO_OPTION);
        if(opc == JOptionPane.YES_OPTION){
            this.dispose();
            TelaLogin.main();
        }
    }//GEN-LAST:event_btnFornecedor1ActionPerformed

    /**
     * @param args the command line arguments
     */
    private static TelaPrincipal tela;
    public static TelaPrincipal getInstance(java.awt.Frame parent, boolean modal) {        
        if (tela == null){
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
             * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
             */
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(GerenciaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(GerenciaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(GerenciaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(GerenciaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>
            
            return new TelaPrincipal(parent, modal);        
        }
        else{
            return tela;
        }
    }
    
    public static void inciar(Funcionario f) {
       TelaPrincipal dialog = TelaPrincipal.getInstance(
                                new javax.swing.JFrame(), true);
        dialog.preprararMostrar(f);
        dialog.setVisible(true);
        

    }
    private void preprararMostrar(Funcionario f) {
        if(f.getCargoFuncionario().equals("Operador")){
            funcionario.setEnabled(false);
            btnFuncionario.setEnabled(false);
            cliente.setEnabled(false);
            btnCliente.setEnabled(false);
            fornecedor.setEnabled(false);
            btnFornecedor.setEnabled(false);
        }else if(f.getCargoFuncionario().equals("Super Operador")){
            funcionario.setEnabled(false);
            btnFuncionario.setEnabled(false);
            fornecedor.setEnabled(false);
            btnFornecedor.setEnabled(false);
            
        }else if(f.getCargoFuncionario().equals("Administrador")){
            
        }else if(f.getCargoFuncionario().equals("Gerente")){
            
        }
        else{
            this.setEnabled(false);
            JOptionPane.showMessageDialog(null, "O Usuário informado possui um cargo inválido. Contate um administrador do sistema para solucionar seu cadastro.", "Falha na Autenticação do Usuário", JOptionPane.ERROR_MESSAGE);
            System.exit(WIDTH);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCliente;
    private javax.swing.JButton btnFornecedor;
    private javax.swing.JButton btnFornecedor1;
    private javax.swing.JButton btnFuncionario;
    private javax.swing.JButton btnVendas;
    private javax.swing.JMenuItem cliente;
    private javax.swing.JMenu dados;
    private javax.swing.JMenuItem fornecedor;
    private javax.swing.JMenuItem funcionario;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuBar principal;
    private javax.swing.JMenu relatorio;
    private javax.swing.JTable tabelaFaltando;
    private javax.swing.JMenuItem vendas;
    // End of variables declaration//GEN-END:variables
}
